apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: formulation-workbench
  namespace: formulation-workbench
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: formulation-workbench
