apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "formulation-workbench.fullname" . }}
  labels:
    {{- include "formulation-workbench.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
