{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "formulation-workbench.fullname" . }}
  labels:
    {{- include "formulation-workbench.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "formulation-workbench.selectorLabels" . | nindent 6 }}
{{- end }}
