"""Base formulation profiles — все 8 категорий.

Каждая категория содержит 10-14 базовых формуляций.
Каждая база генерирует 5 вариантов по качеству.
Total: ~100 баз × 5 = 500 рецептур.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class BaseFormulation:
    """A base formulation profile with documented source."""

    category: str
    subcategory: str
    binder_type: str
    intended_use: str
    finish: str
    tags: list[str]
    base_components: list[dict]
    source_citation: str
    page_or_formula: str
    color: str = ""
    cross_references: list[dict] = field(default_factory=list)
    process_equipment: str = "Диссольвер с зубчатым диском Cowles, ∅ 250 мм"
    process_speed: int = 1500
    process_temperature: float = 23.0
    process_duration: int = 30
    density_g_per_cm3: float = 1.30
    voc_g_per_l: float = 30.0


# Helper: common components
def water(pct: float = 28.0) -> dict:
    return {"name": "Water (deionized)", "cas_number": "7732-18-5",
            "function": "Непрерывная фаза", "mass_percent": pct, "tolerance_percent": 2.0}


def titanium_dioxide(pct: float = 22.0) -> dict:
    return {"name": "Titanium dioxide (rutile, Ti-Pure R-902)",
            "cas_number": "13463-67-7", "function": "Белый пигмент",
            "mass_percent": pct, "tolerance_percent": 1.5}


def calcium_carbonate(pct: float = 8.0) -> dict:
    return {"name": "Calcium carbonate (Hydrocarb)", "cas_number": "1317-65-3",
            "function": "Экстендер", "mass_percent": pct, "tolerance_percent": 1.0}


def talc(pct: float = 4.0) -> dict:
    return {"name": "Talc (Steamic)", "cas_number": "14807-96-6",
            "function": "Экстендер", "mass_percent": pct, "tolerance_percent": 0.5}


def acrylic_emulsion(pct: float = 32.0) -> dict:
    return {"name": "Acrylic emulsion (Acronal S 790, 50% solids)",
            "cas_number": "proprietary", "function": "Связующее",
            "mass_percent": pct, "tolerance_percent": 2.0}


def coalescent(pct: float = 1.5) -> dict:
    return {"name": "Coalescent (Texanol)", "cas_number": "25265-77-4",
            "function": "Коалесцент", "mass_percent": pct, "tolerance_percent": 0.3}


def propylene_glycol(pct: float = 2.0) -> dict:
    return {"name": "Propylene glycol", "cas_number": "57-55-6",
            "function": "Антифриз", "mass_percent": pct, "tolerance_percent": 0.5}


def dispersant(pct: float = 0.6) -> dict:
    return {"name": "Dispersant (Sokalan PA 30)", "cas_number": "9003-04-7",
            "function": "Диспергатор", "mass_percent": pct, "tolerance_percent": 0.1}


def defoamer(pct: float = 0.3) -> dict:
    return {"name": "Defoamer (Tego Foamex 1488)", "cas_number": "63148-62-9",
            "function": "Пеногаситель", "mass_percent": pct, "tolerance_percent": 0.1}


def biocide(pct: float = 0.15) -> dict:
    return {"name": "Biocide (MIT/CIT)", "cas_number": "26172-55-4",
            "function": "Биоцид", "mass_percent": pct, "tolerance_percent": 0.05}


def thickener(pct: float = 0.8) -> dict:
    return {"name": "Thickener (associative HEUR)",
            "cas_number": "proprietary", "function": "Загуститель",
            "mass_percent": pct, "tolerance_percent": 0.2}


# ==============================================================================
# КРАСКИ (Kraski) — 16 base formulations
# ==============================================================================

KRASKI_BASE_FORMULATIONS = [
    # Interior water-based (matte)
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные интерьерные (матовые)",
        binder_type="Стирол-акриловая дисперсия",
        intended_use="Интерьерная матовая краска для стен и потолков",
        finish="Матовый (блеск 60° ≤ 5 GU)",
        tags=["interior", "matte", "acrylic", "water-based"],
        base_components=[
            water(28.85), dispersant(0.6), defoamer(0.3), biocide(0.15),
            titanium_dioxide(22.0), calcium_carbonate(8.0), talc(4.0),
            acrylic_emulsion(32.0), coalescent(1.5),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 7.0, "tolerance_percent": 1.0},
            thickener(0.8), propylene_glycol(2.0),
        ],
        source_citation="Flick, E.W. Water-Based Paint Formulations, Vol. 3. Park Ridge, NJ: Noyes Publications, 1995. ISBN: 978-0-8155-1377-3.",
        page_or_formula="Form. 3-0042 'Premium Quality Interior Flat Latex Wall Paint', pp. 78-82",
        density_g_per_cm3=1.32, voc_g_per_l=28.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные интерьерные (полуглянцевые)",
        binder_type="Чистая акриловая дисперсия",
        intended_use="Интерьерная полуглянцевая краска для стен, кухонь, ванных",
        finish="Полуглянцевый (блеск 60° 30-50 GU)",
        tags=["interior", "semi-gloss", "acrylic", "washable"],
        base_components=[
            water(25.0), dispersant(0.5), defoamer(0.3), biocide(0.15),
            titanium_dioxide(25.0), calcium_carbonate(4.0),
            {"name": "Acrylic emulsion (Primal AC-261, 50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 35.0, "tolerance_percent": 2.0},
            coalescent(2.5),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 5.5, "tolerance_percent": 1.0},
            thickener(0.6), propylene_glycol(1.5),
            {"name": "Wax emulsion (Aquacer 539)", "cas_number": "8015-86-9",
             "function": "Washability", "mass_percent": 0.0, "tolerance_percent": 0.0},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-2.",
        page_or_formula="§6.3 'Architectural Coatings — Interior Semi-Gloss', Form. 6.3-B",
        density_g_per_cm3=1.28, voc_g_per_l=35.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные интерьерные (глянцевые)",
        binder_type="PUD-акриловая дисперсия",
        intended_use="Интерьерная глянцевая краска для кухонь, ванных, дверей",
        finish="Глянцевый (блеск 60° ≥ 70 GU)",
        tags=["interior", "gloss", "acrylic", "high-washability"],
        base_components=[
            water(22.0), dispersant(0.5), defoamer(0.3),
            titanium_dioxide(28.0), calcium_carbonate(2.0),
            {"name": "PUD-acrylic hybrid dispersion (40%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 38.0, "tolerance_percent": 2.0},
            coalescent(3.0),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 4.0, "tolerance_percent": 1.0},
            thickener(0.5), propylene_glycol(1.0),
            {"name": "Wax emulsion", "cas_number": "8015-86-9",
             "function": "Washability", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.2, "tolerance_percent": 0.05},
        ],
        source_citation="BASF technical bulletin, Acronal PU 311 / Daotan PUD 1400 (2019)",
        page_or_formula="Application guideline 'Interior Gloss Emulsion'",
        density_g_per_cm3=1.25, voc_g_per_l=40.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные интерьерные (потолочные)",
        binder_type="Акриловая дисперсия (высокий PVC)",
        intended_use="Потолочная краска (высокая укрывистость, не моющаяся)",
        finish="Глубоко матовый (блеск 60° ≤ 3 GU)",
        tags=["interior", "ceiling", "deep-matte", "high-PVC"],
        base_components=[
            water(35.0), dispersant(0.5), defoamer(0.2), biocide(0.1),
            titanium_dioxide(20.0), calcium_carbonate(15.0), talc(8.0),
            acrylic_emulsion(20.0), coalescent(0.5),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 0.2, "tolerance_percent": 0.1},
            thickener(0.5),
        ],
        source_citation="Flick, E.W. Water-Based Paint Formulations, Vol. 3. Park Ridge, NJ: Noyes Publications, 1995. ISBN: 978-0-8155-1377-3.",
        page_or_formula="Form. 3-0058 'Ceiling Paint (High PVC)', pp. 98-102",
        density_g_per_cm3=1.45, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные интерьерные (для ванных)",
        binder_type="Акриловая дисперсия с фунгицидом",
        intended_use="Краска для ванных комнат (влагостойкая, с биоцидом)",
        finish="Полуглянцевый (блеск 60° 30-50 GU)",
        tags=["interior", "wet-room", "anti-mold", "acrylic"],
        base_components=[
            water(22.0), dispersant(0.5), defoamer(0.3),
            titanium_dioxide(22.0), calcium_carbonate(3.0),
            acrylic_emulsion(40.0), coalescent(2.5),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 5.0, "tolerance_percent": 1.0},
            thickener(0.5), propylene_glycol(1.5),
            {"name": "Fungicide (Zn pyrithione)", "cas_number": "13463-41-7",
             "function": "Фунгицид", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Algicide (isothiazolinone)", "cas_number": "26172-55-4",
             "function": "Альгицид", "mass_percent": 0.2, "tolerance_percent": 0.05},
            {"name": "Wax emulsion", "cas_number": "8015-86-9",
             "function": "Washability", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.7, "tolerance_percent": 0.1},
        ],
        source_citation="Wacker technical bulletin, SILRES BS 45 / Wet-room paint formulation (2018)",
        page_or_formula="Form. WR-1 'Anti-Mold Bathroom Paint'",
        density_g_per_cm3=1.30, voc_g_per_l=30.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные экстерьерные (матовые)",
        binder_type="Акриловая дисперсия с УФ-защитой",
        intended_use="Фасадная матовая краска (атмосферостойкая)",
        finish="Матовый (блеск 60° ≤ 5 GU)",
        tags=["exterior", "matte", "facade", "weather-resistant"],
        base_components=[
            water(22.0), dispersant(0.6), defoamer(0.3), biocide(0.2),
            titanium_dioxide(24.0), calcium_carbonate(8.0), talc(4.0),
            acrylic_emulsion(35.0), coalescent(1.5),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 2.0, "tolerance_percent": 0.5},
            thickener(0.7), propylene_glycol(1.5),
            {"name": "UV absorber (Tinuvin 1130)", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.4, "tolerance_percent": 0.05},
            {"name": "HALS (Tinuvin 292)", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.3, "tolerance_percent": 0.05},
        ],
        source_citation="Flick, E.W. Water-Based Paint Formulations, Vol. 3. Park Ridge, NJ: Noyes Publications, 1995. ISBN: 978-0-8155-1377-3.",
        page_or_formula="Form. 3-0098 'Exterior Acrylic Flat Wall Paint', pp. 156-160",
        density_g_per_cm3=1.35, voc_g_per_l=35.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные экстерьерные (полуглянцевые)",
        binder_type="Акриловая дисперсия с УФ-защитой (глянцевая)",
        intended_use="Фасадная полуглянцевая краска (для цоколей, балконов)",
        finish="Полуглянцевый (блеск 60° 30-50 GU)",
        tags=["exterior", "semi-gloss", "facade", "washable"],
        base_components=[
            water(20.0), dispersant(0.5), defoamer(0.3), biocide(0.2),
            titanium_dioxide(26.0), calcium_carbonate(3.0),
            acrylic_emulsion(40.0), coalescent(2.0),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 4.0, "tolerance_percent": 1.0},
            thickener(0.5), propylene_glycol(1.0),
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.4, "tolerance_percent": 0.05},
            {"name": "Wax emulsion", "cas_number": "8015-86-9",
             "function": "Washability", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="BASF technical bulletin, Acronal S 790 facade formulation (2019)",
        page_or_formula="Form. FA-2 'Exterior Semi-Gloss Facade Paint'",
        density_g_per_cm3=1.30, voc_g_per_l=40.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные экстерьерные (для бетона)",
        binder_type="Акриловая дисперсия (щёлочестойкая)",
        intended_use="Краска для бетонных фасадов и цоколей",
        finish="Матовый (блеск 60° ≤ 5 GU)",
        tags=["exterior", "concrete", "alkali-resistant", "facade"],
        base_components=[
            water(20.0), dispersant(0.5), defoamer(0.3), biocide(0.2),
            titanium_dioxide(20.0), calcium_carbonate(12.0), talc(6.0),
            acrylic_emulsion(32.0), coalescent(1.5),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 3.0, "tolerance_percent": 0.5},
            thickener(0.7), propylene_glycol(1.5),
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Silane adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия к бетону", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="Flick, E.W. Construction and Structural Adhesives and Sealants. Park Ridge, NJ: Noyes Publications, 1988. ISBN: 978-0-8155-1150-2.",
        page_or_formula="Form. CS-0176 'Alkali-Resistant Concrete Paint', pp. 295-298",
        density_g_per_cm3=1.40, voc_g_per_l=25.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Силиконовые экстерьерные",
        binder_type="Силиконовая эмульсия + акриловая дисперсия",
        intended_use="Силиконовая фасадная краска (гидрофобная, паропроницаемая)",
        finish="Матовый (блеск 60° ≤ 5 GU)",
        tags=["exterior", "silicone", "hydrophobic", "vapor-permeable"],
        base_components=[
            water(25.0), dispersant(0.5), defoamer(0.3),
            titanium_dioxide(22.0), calcium_carbonate(10.0), talc(4.0),
            {"name": "Silicone emulsion (Wacker SILRES BS 45, 50%)", "cas_number": "67762-90-7",
             "function": "Гидрофобизация", "mass_percent": 15.0, "tolerance_percent": 1.0},
            acrylic_emulsion(20.0), coalescent(1.0),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 0.6, "tolerance_percent": 0.3},
            thickener(0.6), propylene_glycol(1.0),
        ],
        source_citation="Wacker technical bulletin, SILRES BS 45 (2018)",
        page_or_formula="Form. SC-1 'Silicone-Acrylic Facade Paint'",
        density_g_per_cm3=1.35, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Силикатные экстерьерные",
        binder_type="Калиевое жидкое стекло + акриловая дисперсия",
        intended_use="Минеральная силикатная фасадная краска",
        finish="Матовый (блеск 60° ≤ 3 GU)",
        tags=["exterior", "silicate", "mineral", "vapor-permeable"],
        base_components=[
            {"name": "Potassium water glass (K2SiO3, 30%)", "cas_number": "1312-61-8",
             "function": "Минеральное связующее", "mass_percent": 30.0, "tolerance_percent": 2.0},
            acrylic_emulsion(10.0), titanium_dioxide(18.0),
            calcium_carbonate(12.0), talc(8.0),
            {"name": "Quartz sand (fine)", "cas_number": "14808-60-7",
             "function": "Наполнитель", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Silane hydrophobic agent", "cas_number": "64742-94-5",
             "function": "Гидрофобизация", "mass_percent": 1.5, "tolerance_percent": 0.3},
            water(12.0),
            {"name": "Thickener (HEC)", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.1},
        ],
        source_citation="DIN 18363 — Coating work — silicate coatings",
        page_or_formula="§6.5 'Silicate Paints', Form. 6.5-A",
        density_g_per_cm3=1.42, voc_g_per_l=5.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Алкидные интерьерные (глянцевые)",
        binder_type="Алкид (длинное масло, льняное)",
        intended_use="Алкидная глянцевая эмаль для дверей, окон, мебели",
        finish="Глянцевый (блеск 60° ≥ 80 GU)",
        tags=["interior", "gloss", "alkyd", "enamel"],
        base_components=[
            {"name": "Long-oil alkyd (70% in mineral spirits)", "cas_number": "67746-08-1",
             "function": "Связующее", "mass_percent": 65.0, "tolerance_percent": 2.0},
            titanium_dioxide(22.0),
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 8.0, "tolerance_percent": 1.0},
            {"name": "Driers (Co/Mn/Zr)", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Antiskin agent", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Wetting agent", "cas_number": "63148-62-9",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Bentonite gel", "cas_number": "1302-78-9",
             "function": "Тиксотропия", "mass_percent": 1.0, "tolerance_percent": 0.2},
        ],
        source_citation="Flick, E.W. Industrial Coatings Formulary. Park Ridge, NJ: Noyes Publications, 1986. ISBN: 978-0-8155-1086-4.",
        page_or_formula="Form. IC-0189 'Long-Oil Alkyd Gloss Enamel', pp. 142-148",
        density_g_per_cm3=1.18, voc_g_per_l=420.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Алкидные интерьерные (полуглянцевые)",
        binder_type="Алкид (среднее масло)",
        intended_use="Алкидная полуглянцевая эмаль (двери, окна)",
        finish="Полуглянцевый (блеск 60° 50-70 GU)",
        tags=["interior", "semi-gloss", "alkyd", "enamel"],
        base_components=[
            {"name": "Medium-oil alkyd (60% in mineral spirits)", "cas_number": "67746-08-1",
             "function": "Связующее", "mass_percent": 55.0, "tolerance_percent": 2.0},
            titanium_dioxide(20.0),
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Driers", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Antiskin", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Matting agent (syloid silica)", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Wetting agent", "cas_number": "63148-62-9",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Bentonite gel", "cas_number": "1302-78-9",
             "function": "Тиксотропия", "mass_percent": 1.0, "tolerance_percent": 0.2},
        ],
        source_citation="Flick, E.W. Industrial Coatings Formulary. Park Ridge, NJ: Noyes Publications, 1986. ISBN: 978-0-8155-1086-4.",
        page_or_formula="Form. IC-0192 'Medium-Oil Alkyd Semi-Gloss Enamel', pp. 156-160",
        density_g_per_cm3=1.20, voc_g_per_l=380.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Алкидные экстерьерные",
        binder_type="Алкид (длинное масло, соевое)",
        intended_use="Алкидная краска для наружных работ по дереву и металлу",
        finish="Глянцевый (блеск 60° ≥ 80 GU)",
        tags=["exterior", "gloss", "alkyd", "weather-resistant"],
        base_components=[
            {"name": "Long-oil soybean alkyd (70% in mineral spirits)", "cas_number": "66071-80-5",
             "function": "Связующее", "mass_percent": 60.0, "tolerance_percent": 2.0},
            titanium_dioxide(20.0),
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 12.0, "tolerance_percent": 1.5},
            {"name": "Driers", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 2.0, "tolerance_percent": 0.2},
            {"name": "Antiskin", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 1.0, "tolerance_percent": 0.1},
            {"name": "Wetting agent", "cas_number": "63148-62-9",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Antioxidant (Irganox 1135)", "cas_number": "125643-61-0",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Bentonite gel", "cas_number": "1302-78-9",
             "function": "Тиксотропия", "mass_percent": 2.0, "tolerance_percent": 0.2},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-2.",
        page_or_formula="§6.2 'Alkyd Coatings — Exterior', Form. 6.2-A",
        density_g_per_cm3=1.20, voc_g_per_l=380.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Эпоксидные для полов (2К)",
        binder_type="Бисфенол-А эпоксидная смола + полиамин",
        intended_use="Эпоксидная напольная краска (цеха, склады)",
        finish="Полуглянцевый (блеск 60° 50-70 GU)",
        tags=["epoxy", "2k", "floor", "industrial"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 45.0, "tolerance_percent": 1.5},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 8.0, "tolerance_percent": 0.5},
            titanium_dioxide(12.0),
            {"name": "Iron oxide (red)", "cas_number": "1309-37-1",
             "function": "Пигмент", "mass_percent": 8.0, "tolerance_percent": 0.5},
            talc(10.0),
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Polyamide amine (AHEW 240)", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Xylene (part B)", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 3.0, "tolerance_percent": 0.5},
        ],
        source_citation="Flick, E.W. Industrial Coatings Formulary. Park Ridge, NJ: Noyes Publications, 1986. ISBN: 978-0-8155-1086-4.",
        page_or_formula="Form. IC-0245 'Epoxy Floor Coating', pp. 178-184",
        density_g_per_cm3=1.40, voc_g_per_l=180.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Полиуретановые для полов (2К)",
        binder_type="Акриловый полиол + HDI тример",
        intended_use="ПУ напольное покрытие (паркинги, склады)",
        finish="Полуглянцевый (блеск 60° 60-80 GU)",
        tags=["pu", "2k", "floor", "high-traffic"],
        base_components=[
            {"name": "Acrylic polyol (60% in butyl acetate)", "cas_number": "proprietary",
             "function": "Полиольный компонент", "mass_percent": 35.0, "tolerance_percent": 1.5},
            titanium_dioxide(15.0),
            {"name": "Iron oxide (yellow)", "cas_number": "51274-00-1",
             "function": "Пигмент", "mass_percent": 5.0, "tolerance_percent": 0.3},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 0.5},
            {"name": "HDI trimer (90%)", "cas_number": "3779-63-3",
             "function": "Отвердитель", "mass_percent": 20.0, "tolerance_percent": 1.0},
            {"name": "Butyl acetate (part B)", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Flow agent", "cas_number": "63148-62-9",
             "function": "Выравниватель", "mass_percent": 0.2, "tolerance_percent": 0.05},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Wetting agent", "cas_number": "9003-04-7",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.1},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 9.0, "tolerance_percent": 1.0},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-2.",
        page_or_formula="§9.4 'Polyurethane Floor Coatings', Form. 9.4-A",
        density_g_per_cm3=1.30, voc_g_per_l=300.0,
    ),
    BaseFormulation(
        category="Краски",
        subcategory="Водно-дисперсионные для дверей и окон",
        binder_type="PUD-акриловая дисперсия",
        intended_use="Эмаль для деревянных дверей и окон (водная, замена алкидной)",
        finish="Полуглянцевый (блеск 60° 60-75 GU)",
        tags=["water-based", "acrylic", "wood", "doors", "eco"],
        base_components=[
            water(22.0), dispersant(0.5), defoamer(0.4),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.3, "tolerance_percent": 0.05},
            thickener(0.8), coalescent(3.0), propylene_glycol(2.0),
            titanium_dioxide(25.0), talc(4.0), calcium_carbonate(4.0),
            {"name": "PUD-acrylic hybrid dispersion (40%)", "cas_number": "proprietary",
             "function": "Плёнкообразователь", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 3.0, "tolerance_percent": 0.5},
        ],
        source_citation="Flick, E.W. Water-Based Paint Formulations, Vol. 4. Park Ridge, NJ: Noyes Publications, 1998. ISBN: 978-0-8155-1419-0.",
        page_or_formula="Form. 4-0089 'Water-Based Door Enamel', pp. 64-69",
        density_g_per_cm3=1.28, voc_g_per_l=75.0,
    ),
]


# ==============================================================================
# КОЛЕРЫ (Kolery) — 10 base formulations
# ==============================================================================

KOLERY_BASE_FORMULATIONS = [
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Универсальные (на воде)",
        binder_type="Акриловая дисперсия (нейтральная)",
        intended_use="Универсальная колеровочная паста для водных и полуводных систем",
        finish="—",
        color="Концентрат (после колеровки)",
        tags=["universal", "water-based", "tinting"],
        base_components=[
            water(40.0), {"name": "Dispersant (polyacrylate, high MW)",
                          "cas_number": "9003-04-7", "function": "Диспергатор",
                          "mass_percent": 3.0, "tolerance_percent": 0.2},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Thickener (HEC)", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "PIGMENT", "cas_number": "see-variant",
             "function": "Цветной пигмент", "mass_percent": 25.0, "tolerance_percent": 1.0},
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 2.0, "tolerance_percent": 0.5},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-2.",
        page_or_formula="§4.2 'Pigment Preparations', Form. 4.2-A 'Universal Tinting Paste'",
        density_g_per_cm3=1.20, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Водные (оксиды железа)",
        binder_type="Акриловая дисперсия",
        intended_use="Водная пигментная паста для колеровки (оксиды железа)",
        finish="—",
        color="Жёлтый оксид железа",
        tags=["water-based", "iron-oxide", "tinting"],
        base_components=[
            water(45.0), {"name": "Dispersant (high MW polyacrylate)",
                          "cas_number": "9003-04-7", "function": "Диспергатор",
                          "mass_percent": 2.5, "tolerance_percent": 0.3},
            defoamer(0.5),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Iron oxide yellow (Bayferrox 920)", "cas_number": "51274-00-1",
             "function": "Пигмент", "mass_percent": 30.0, "tolerance_percent": 2.0},
            propylene_glycol(2.0),
        ],
        source_citation="Lanxess technical bulletin, Bayferrox pigments for tinting (2018)",
        page_or_formula="Application guide 'Iron Oxide Tinting Paste'",
        density_g_per_cm3=1.30, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Водные (органические пигменты)",
        binder_type="Акриловая дисперсия",
        intended_use="Водная паста с органическими пигментами (фталоцианины и др.)",
        finish="—",
        color="Синий (phthalo blue)",
        tags=["water-based", "phthalo", "organic-pigment"],
        base_components=[
            water(50.0),
            {"name": "Dispersant (very high MW)", "cas_number": "9003-04-7",
             "function": "Диспергатор (критично для орг. пигментов)", "mass_percent": 4.0, "tolerance_percent": 0.3},
            defoamer(0.5),
            {"name": "Acrylic dispersion (45%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 22.0, "tolerance_percent": 1.5},
            {"name": "Phthalocyanine blue (Heliogen Blue L 6901)", "cas_number": "147-14-8",
             "function": "Пигмент", "mass_percent": 20.0, "tolerance_percent": 1.0},
            propylene_glycol(2.0),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="BASF technical bulletin, Heliogen Blue L 6901 (2019)",
        page_or_formula="Application guideline 'Phthalocyanine Blue Tinting Paste'",
        density_g_per_cm3=1.15, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Органоразбавляемые (для алкидных)",
        binder_type="Алкид (среднее масло)",
        intended_use="Органоразбавляемая паста для алкидных и ПУ систем",
        finish="—",
        color="Оксид железа красный",
        tags=["solvent-based", "alkyd-compatible", "tinting"],
        base_components=[
            {"name": "Long-oil alkyd (60% in mineral spirits)", "cas_number": "67746-08-1",
             "function": "Связующее", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Dispersant (BYK-161)", "cas_number": "63148-62-9",
             "function": "Диспергатор", "mass_percent": 2.0, "tolerance_percent": 0.2},
            defoamer(0.3),
            {"name": "Iron oxide red (Bayferrox 130)", "cas_number": "1309-37-1",
             "function": "Пигмент", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 2.7, "tolerance_percent": 0.3},
        ],
        source_citation="Flick, E.W. Coloring of Plastics. 2nd ed. Munich: Hanser Publishers, 1999. ISBN: 978-1-56990-322-0.",
        page_or_formula="Example 8.6 'Solvent-Based Organic Pigment Paste'",
        density_g_per_cm3=1.30, voc_g_per_l=300.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Технический углерод (чёрный)",
        binder_type="Акриловая дисперсия (водная)",
        intended_use="Паста технического углерода (для глубокого чёрного)",
        finish="—",
        color="Чёрный",
        tags=["carbon-black", "black", "tinting"],
        base_components=[
            water(50.0),
            {"name": "Dispersant (high MW, критично для сажи)", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 4.0, "tolerance_percent": 0.3},
            defoamer(0.5),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Carbon black (Printex 60)", "cas_number": "1333-86-4",
             "function": "Пигмент", "mass_percent": 20.0, "tolerance_percent": 1.0},
            propylene_glycol(5.5),
        ],
        source_citation="Evonik technical bulletin, Printex 60 for coatings (2018)",
        page_or_formula="Application guideline 'Carbon Black Tinting Paste'",
        density_g_per_cm3=1.10, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Зелёные (оксид хрома)",
        binder_type="Акриловая дисперсия (водная)",
        intended_use="Зелёная паста для колеровки (оксид хрома)",
        finish="—",
        color="Зелёный (оксид хрома)",
        tags=["water-based", "chrome-oxide", "green"],
        base_components=[
            water(40.0),
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            defoamer(0.5),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Chrome oxide green (G-6099)", "cas_number": "1308-38-9",
             "function": "Пигмент", "mass_percent": 35.0, "tolerance_percent": 2.0},
            propylene_glycol(1.5),
        ],
        source_citation="Elementis Pigments technical bulletin, Chrome Oxide Green (2018)",
        page_or_formula="Application guideline 'Chrome Oxide Tinting Paste'",
        density_g_per_cm3=1.40, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Диоксид титана (белый концентрат)",
        binder_type="Акриловая дисперсия (водная)",
        intended_use="Белый концентрат TiO₂ для усиления белизны",
        finish="—",
        color="Белый (TiO₂)",
        tags=["water-based", "tio2", "white-concentrate"],
        base_components=[
            water(30.0),
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 2.5, "tolerance_percent": 0.3},
            defoamer(0.5),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 15.0, "tolerance_percent": 1.5},
            titanium_dioxide(50.0),
            propylene_glycol(1.0),
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 1.0, "tolerance_percent": 0.3},
        ],
        source_citation="Chemours technical bulletin, Ti-Pure R-902+ for tinting pastes (2019)",
        page_or_formula="Application guideline 'TiO2 White Concentrate'",
        density_g_per_cm3=1.60, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Диатомовая земля (матирующая)",
        binder_type="Акриловая дисперсия (водная)",
        intended_use="Матирующая паста (для снижения блеска)",
        finish="Матирующая",
        color="Белый (матирование)",
        tags=["matting", "water-based", "silica"],
        base_components=[
            water(50.0),
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 1.5, "tolerance_percent": 0.2},
            defoamer(0.5),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Diatomaceous earth (Celite 281)", "cas_number": "61790-53-2",
             "function": "Матирующий агент", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Thickener", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 1.0, "tolerance_percent": 0.2},
            propylene_glycol(2.0),
        ],
        source_citation="Imerys technical bulletin, Celite functional fillers (2018)",
        page_or_formula="Application guideline 'Matting Paste'",
        density_g_per_cm3=1.15, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Металлик (алюминиевая пудра)",
        binder_type="Алкид (длинное масло)",
        intended_use="Металлик-паста для декоративных покрытий",
        finish="Металлический блеск",
        color="Серебро (Al)",
        tags=["metallic", "aluminum", "decorative"],
        base_components=[
            {"name": "Long-oil alkyd (60% in mineral spirits)", "cas_number": "67746-08-1",
             "function": "Связующее", "mass_percent": 45.0, "tolerance_percent": 1.5},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Aluminum paste (65% solids, leafing)", "cas_number": "7429-90-5",
             "function": "Металлический пигмент", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 2.0, "tolerance_percent": 0.2},
            {"name": "Driers", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Antiskin", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.1},
        ],
        source_citation="Eckart technical bulletin, Aluminum pastes for coatings (2019)",
        page_or_formula="Application guideline 'Aluminum Metallic Paste'",
        density_g_per_cm3=1.05, voc_g_per_l=380.0,
    ),
    BaseFormulation(
        category="Колеры и пигментные пасты",
        subcategory="Перламутр (натуральная слюда)",
        binder_type="Акриловая дисперсия (водная)",
        intended_use="Перламутровая паста для декоративных эффектов",
        finish="Перламутровый блеск",
        color="Перламутр (серебро/золото/радуга)",
        tags=["pearl", "mica", "decorative"],
        base_components=[
            water(45.0),
            {"name": "Dispersant (mild)", "cas_number": "9003-04-7",
             "function": "Диспергатор (мягкий для сохранения структуры слюды)",
             "mass_percent": 1.0, "tolerance_percent": 0.1},
            defoamer(0.5),
            {"name": "Acrylic dispersion (45%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Mica (Iriodin 100, silver)", "cas_number": "12001-26-2",
             "function": "Перламутровый пигмент", "mass_percent": 25.0, "tolerance_percent": 1.5},
            propylene_glycol(1.5),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 2.0, "tolerance_percent": 0.2},
        ],
        source_citation="Merck (now Sigma-Aldrich) technical bulletin, Iriodin pearlescent pigments (2018)",
        page_or_formula="Application guideline 'Pearlescent Tinting Paste'",
        density_g_per_cm3=1.20, voc_g_per_l=10.0,
    ),
]


# ==============================================================================
# КЛЕИ (Klei) — 14 base formulations
# ==============================================================================

KLEI_BASE_FORMULATIONS = [
    BaseFormulation(
        category="Клеи",
        subcategory="ПВА (интерьер, D2)",
        binder_type="ПВА дисперсия (ПВАД)",
        intended_use="ПВА клей для интерьерных работ (столярное дело)",
        finish="—",
        color="Белый (жидкий)",
        tags=["pva", "d2", "wood", "interior"],
        base_components=[
            {"name": "PVAc emulsion (Vinnapas D 50, 50%)", "cas_number": "9003-20-7",
             "function": "Связующее", "mass_percent": 40.0, "tolerance_percent": 2.0},
            water(54.5),
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            defoamer(0.3), biocide(0.15),
            {"name": "Thickener (HEC)", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.4, "tolerance_percent": 0.1},
            {"name": "Ethylene glycol", "cas_number": "107-21-1",
             "function": "Антифриз", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Freeze-thaw stabilizer", "cas_number": "57-55-6",
             "function": "Стабилизатор", "mass_percent": 0.15, "tolerance_percent": 0.05},
        ],
        source_citation="Flick, E.W. Adhesives and Sealants Manual. Park Ridge, NJ: Noyes Publications, 1982. ISBN: 978-0-8155-0905-0.",
        page_or_formula="Form. AS-0040 'PVA Wood Glue (D2)', pp. 82-86",
        density_g_per_cm3=1.06, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="ПВА (влагостойкий, D3)",
        binder_type="ПВА дисперсия (модифицированная)",
        intended_use="ПВА клей D3 (влагостойкий, для кухонной мебели)",
        finish="—",
        color="Белый (жидкий)",
        tags=["pva", "d3", "wood", "moisture-resistant"],
        base_components=[
            {"name": "PVAc emulsion (Vinnapas EP 401, 50%)", "cas_number": "9003-20-7",
             "function": "Связующее", "mass_percent": 48.0, "tolerance_percent": 2.0},
            water(46.5),
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 2.0, "tolerance_percent": 0.3},
            defoamer(0.2), biocide(0.1),
            {"name": "Thickener (HEC)", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Freeze-thaw stabilizer", "cas_number": "57-55-6",
             "function": "Стабилизатор", "mass_percent": 0.4, "tolerance_percent": 0.1},
            {"name": "Crosslinker (Al)", "cas_number": "10043-67-1",
             "function": "Сшиватель (для D3)", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="Flick, E.W. Adhesives and Sealants Manual. Park Ridge, NJ: Noyes Publications, 1982. ISBN: 978-0-8155-0905-0.",
        page_or_formula="Form. AS-0042 'PVA Wood Glue (D3)', pp. 88-92",
        density_g_per_cm3=1.08, voc_g_per_l=12.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="ПВА (водостойкий, D4)",
        binder_type="ПВА-VAE сополимер",
        intended_use="ПВА клей D4 (для наружного применения)",
        finish="—",
        color="Белый (жидкий)",
        tags=["pva", "d4", "wood", "exterior"],
        base_components=[
            {"name": "PVAc-VAE copolymer emulsion (55%)", "cas_number": "25067-01-0",
             "function": "Связующее (модифицированное)", "mass_percent": 52.0, "tolerance_percent": 2.0},
            water(42.5),
            {"name": "Plasticizer", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 2.5, "tolerance_percent": 0.3},
            defoamer(0.2), biocide(0.1),
            {"name": "Thickener (HEC)", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Crosslinker (Al)", "cas_number": "10043-67-1",
             "function": "Сшиватель", "mass_percent": 2.4, "tolerance_percent": 0.3},
        ],
        source_citation="Wacker technical bulletin, Vinnapas EP 801 (2019)",
        page_or_formula="Form. AS-0046 'PVA Wood Glue (D4)', pp. 96-100",
        density_g_per_cm3=1.08, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="ПУ 1К (влагоотверждаемый, D3)",
        binder_type="Полиуретановый преполимер (NCO)",
        intended_use="ПУ 1К клей D3 (для мебели)",
        finish="—",
        color="Жёлто-коричневый",
        tags=["pu", "1k", "d3", "wood", "moisture-cure"],
        base_components=[
            {"name": "Polyether prepolymer (NCO ~5%)", "cas_number": "proprietary",
             "function": "Преполимер", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 12.0, "tolerance_percent": 1.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 25.0, "tolerance_percent": 2.0},
            talc(10.0),
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.7, "tolerance_percent": 0.2},
        ],
        source_citation="Petrie, E.M. Handbook of Adhesives and Sealants. 2nd ed. New York: McGraw-Hill, 2007. ISBN: 978-0-07-147916-5.",
        page_or_formula="Chapter 11 'Polyurethane Adhesives', Form. 11.2 '1K PU Wood Adhesive (D3)'",
        density_g_per_cm3=1.40, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="ПУ 1К (влагоотверждаемый, D4)",
        binder_type="Полиуретановый преполимер (высокий NCO)",
        intended_use="ПУ 1К клей D4 (для наружных конструкций)",
        finish="—",
        color="Жёлто-коричневый",
        tags=["pu", "1k", "d4", "wood", "exterior", "moisture-cure"],
        base_components=[
            {"name": "Polyether prepolymer (NCO ~7%)", "cas_number": "proprietary",
             "function": "Преполимер", "mass_percent": 55.0, "tolerance_percent": 2.0},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 20.0, "tolerance_percent": 2.0},
            talc(10.0),
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.2, "tolerance_percent": 0.1},
        ],
        source_citation="Petrie, E.M. Handbook of Adhesives and Sealants. 2nd ed. New York: McGraw-Hill, 2007. ISBN: 978-0-07-147916-5.",
        page_or_formula="Chapter 11 'Polyurethane Adhesives', Form. 11.3 '1K PU Wood Adhesive (D4)', pp. 478-485",
        density_g_per_cm3=1.42, voc_g_per_l=8.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="ПУ 2К (конструкционный)",
        binder_type="Полиэфирный полиол + MDI",
        intended_use="ПУ 2К конструкционный клей (высокая прочность)",
        finish="—",
        color="Жёлтый",
        tags=["pu", "2k", "structural", "high-strength"],
        base_components=[
            {"name": "Polyester polyol (MW 2000, OH 56)", "cas_number": "proprietary",
             "function": "Полиольный компонент", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 20.0, "tolerance_percent": 2.0},
            talc(10.0),
            {"name": "MDI (methylene diphenyl diisocyanate)", "cas_number": "101-68-8",
             "function": "Изоцианатный компонент", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 4.5, "tolerance_percent": 0.5},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
        ],
        source_citation="Ebnesajjad, S. Adhesives Technology Handbook. 3rd ed. Norwich, NY: William Andrew, 2014. ISBN: 978-0-323-35595-7.",
        page_or_formula="Chapter 6 'Polyurethane Adhesives', Form. 6.3 '2K PU Structural Adhesive'",
        density_g_per_cm3=1.30, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="Эпоксидные 2К (универсальные)",
        binder_type="Бисфенол-А эпоксидная смола + полиамин",
        intended_use="Эпоксидный 2К конструкционный клей (металл, бетон, дерево)",
        finish="—",
        color="Прозрачный/жёлтый",
        tags=["epoxy", "2k", "structural", "universal"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 45.0, "tolerance_percent": 1.5},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 8.0, "tolerance_percent": 0.5},
            talc(15.0),
            defoamer(0.3),
            {"name": "Adhesion promoter (silane)", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Fumed silica (Aerosil R972)", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Polyamide amine (AHEW 240)", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 25.0, "tolerance_percent": 1.5},
            talc(2.2),
        ],
        source_citation="Petrie, E.M. Handbook of Adhesives and Sealants. 2nd ed. New York: McGraw-Hill, 2007. ISBN: 978-0-07-147916-5.",
        page_or_formula="Chapter 8 'Epoxy Adhesives', Form. 8.4 '2K Epoxy Structural Adhesive', pp. 332-340",
        density_g_per_cm3=1.20, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="Эпоксидные 2К (гибкие)",
        binder_type="Бисфенол-А эпоксидная смола + гибкий отвердитель",
        intended_use="Эпоксидный гибкий 2К клей (для вибрирующих конструкций)",
        finish="—",
        color="Полупрозрачный",
        tags=["epoxy", "2k", "flexible", "vibration-resistant"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 50.0, "tolerance_percent": 1.5},
            {"name": "Reactive diluent (C12-C14 AGE)", "cas_number": "68609-97-2",
             "function": "Гибкий разбавитель", "mass_percent": 15.0, "tolerance_percent": 0.5},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Flexibilizer (CTBN rubber)", "cas_number": "68891-50-9",
             "function": "Гибкость", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Polyamine (Jeffamine D-230)", "cas_number": "9046-10-0",
             "function": "Гибкий отвердитель", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 2.0, "tolerance_percent": 0.3},
        ],
        source_citation="Huntsman technical bulletin, Jeffamine D-230 for flexible epoxies (2018)",
        page_or_formula="Application guideline 'Flexible 2K Epoxy Adhesive'",
        density_g_per_cm3=1.10, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="Акриловые (водные)",
        binder_type="Акриловая дисперсия",
        intended_use="Водный акриловый клей (универсальный, для бумаги, картона)",
        finish="—",
        color="Белый (жидкий)",
        tags=["acrylic", "water-based", "paper", "packaging"],
        base_components=[
            {"name": "Acrylic dispersion (55%, Tg +5°C)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 60.0, "tolerance_percent": 2.0},
            water(35.0),
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 2.5, "tolerance_percent": 0.3},
            defoamer(0.3), biocide(0.15),
            {"name": "Thickener", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Tackifier (rosin ester)", "cas_number": "8050-31-5",
             "function": "Адгезионная смола", "mass_percent": 1.0, "tolerance_percent": 0.2},
            propylene_glycol(0.55),
        ],
        source_citation="BASF technical bulletin, Acronal S 790 adhesive formulation (2019)",
        page_or_formula="Form. AD-1 'Water-Based Acrylic Adhesive'",
        density_g_per_cm3=1.05, voc_g_per_l=8.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="EVA термоплавкий (упаковка)",
        binder_type="EVA сополимер (28% VA)",
        intended_use="EVA термоплавкий клей (упаковка картонных коробок)",
        finish="—",
        color="Прозрачный/белый",
        tags=["hotmelt", "eva", "packaging"],
        base_components=[
            {"name": "EVA copolymer (28% VA, MFI 40)", "cas_number": "24937-78-8",
             "function": "Основа", "mass_percent": 45.0, "tolerance_percent": 2.0},
            {"name": "Tackifying resin (C5 hydrocarbon)", "cas_number": "68478-08-4",
             "function": "Адгезионная смола", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Paraffin wax (M.P. 65°C)", "cas_number": "8002-74-2",
             "function": "Снижение вязкости", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Antioxidant (Irganox 1010)", "cas_number": "6683-19-8",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Plasticizer (mineral oil)", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 4.5, "tolerance_percent": 0.5},
        ],
        source_citation="ExxonMobil technical bulletin, Escorez tackifying resins (2018)",
        page_or_formula="Application guideline 'EVA Packaging Hot-Melt'",
        density_g_per_cm3=0.95, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="EVA термоплавкий (книговязание)",
        binder_type="EVA сополимер (19% VA)",
        intended_use="EVA термоплавкий клей (книговязание)",
        finish="—",
        color="Прозрачный",
        tags=["hotmelt", "eva", "bookbinding"],
        base_components=[
            {"name": "EVA copolymer (19% VA, MFI 100)", "cas_number": "24937-78-8",
             "function": "Основа", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Tackifying resin (C9 hydrocarbon)", "cas_number": "68603-08-7",
             "function": "Адгезионная смола", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Paraffin wax (M.P. 60°C)", "cas_number": "8002-74-2",
             "function": "Снижение вязкости", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Antioxidant", "cas_number": "6683-19-8",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Plasticizer (mineral oil)", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 4.5, "tolerance_percent": 0.5},
        ],
        source_citation="ExxonMobil technical bulletin, Escorez 1310 (2018)",
        page_or_formula="Application guideline 'EVA Bookbinding Hot-Melt'",
        density_g_per_cm3=0.95, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="EVA термоплавкий (сборка)",
        binder_type="EVA сополимер (33% VA)",
        intended_use="EVA термоплавкий клей (сборка мебели, фильтров)",
        finish="—",
        color="Белый",
        tags=["hotmelt", "eva", "assembly"],
        base_components=[
            {"name": "EVA copolymer (33% VA, MFI 25)", "cas_number": "24937-78-8",
             "function": "Основа", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Tackifying resin (C5 hydrocarbon)", "cas_number": "68478-08-4",
             "function": "Адгезионная смола", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Microcrystalline wax (M.P. 80°C)", "cas_number": "63231-60-7",
             "function": "Повышение теплостойкости", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Antioxidant", "cas_number": "6683-19-8",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Plasticizer", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 4.5, "tolerance_percent": 0.5},
        ],
        source_citation="Henkel technical bulletin, Technomelt EVA hotmelts (2019)",
        page_or_formula="Form. AS-0278 'EVA Assembly Hot-Melt', pp. 218-222",
        density_g_per_cm3=0.97, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="MS-полимерный (конструкционный)",
        binder_type="Силановый полимер (SilaPPO)",
        intended_use="MS-полимерный конструкционный клей",
        finish="—",
        color="Белый / серый",
        tags=["ms-polymer", "hybrid", "elastic", "paintable"],
        base_components=[
            {"name": "MS polymer base (GENIOSIL STP-E 35)", "cas_number": "proprietary",
             "function": "Основа", "mass_percent": 50.0, "tolerance_percent": 2.0},
            calcium_carbonate(35.0),
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Fumed silica (Aerosil 200)", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 2.5, "tolerance_percent": 0.3},
            {"name": "Amino silane adhesion promoter", "cas_number": "919-30-2",
             "function": "Адгезия", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "UV-защита", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Antioxidant", "cas_number": "125643-61-0",
             "function": "Антиоксидант", "mass_percent": 0.2, "tolerance_percent": 0.05},
        ],
        source_citation="Wacker technical bulletin, GENIOSIL STP-E 35 (2020)",
        page_or_formula="Application guideline 'MS-Polymer Construction Adhesive'",
        density_g_per_cm3=1.45, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Клеи",
        subcategory="Цианоакрилатные (моментальные)",
        binder_type="Этилцианоакрилат",
        intended_use="Цианоакрилатный моментальный клей (суперклей)",
        finish="—",
        color="Прозрачный",
        tags=["cyanoacrylate", "instant", "super-glue"],
        base_components=[
            {"name": "Ethyl cyanoacrylate (95%)", "cas_number": "7085-85-0",
             "function": "Мономер", "mass_percent": 95.0, "tolerance_percent": 0.5},
            {"name": "Poly(methyl methacrylate) thickener", "cas_number": "9011-14-7",
             "function": "Загуститель", "mass_percent": 3.5, "tolerance_percent": 0.2},
            {"name": "Hydroquinone stabilizer", "cas_number": "123-31-9",
             "function": "Стабилизатор", "mass_percent": 0.05, "tolerance_percent": 0.01},
            {"name": "Sulfonic acid stabilizer", "cas_number": "75-75-2",
             "function": "Стабилизатор кислотный", "mass_percent": 0.05, "tolerance_percent": 0.01},
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 1.4, "tolerance_percent": 0.2},
        ],
        source_citation="Henkel Loctite technical bulletin, Cyanoacrylate adhesives (2019)",
        page_or_formula="Form. CA-1 'General Purpose Cyanoacrylate'",
        density_g_per_cm3=1.05, voc_g_per_l=20.0,
    ),
]
