"""Base formulation profiles — оставшиеся 4 категории."""

from base_formulations import BaseFormulation, water, titanium_dioxide, calcium_carbonate, talc, acrylic_emulsion, coalescent, propylene_glycol, dispersant, defoamer, biocide, thickener


# ==============================================================================
# ГЕРМЕТИКИ (Germetiki) — 12 base formulations
# ==============================================================================

GERMETIKI_BASE_FORMULATIONS = [
    BaseFormulation(
        category="Герметики",
        subcategory="Силиконовые (ацетокси, универсальные)",
        binder_type="PDMS + ацетоксисилан",
        intended_use="Универсальный силиконовый герметик (строительство)",
        finish="—",
        color="Прозрачный",
        tags=["silicone", "acetoxy", "construction", "universal"],
        base_components=[
            {"name": "Polydimethylsiloxane (PDMS, 100,000 cSt)", "cas_number": "63148-62-9",
             "function": "Основа", "mass_percent": 45.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate (treated)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Mineral oil (plasticizer)", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 8.0, "tolerance_percent": 1.0},
            {"name": "Methyltriacetoxysilane", "cas_number": "4253-34-3",
             "function": "Сшиватель (ацетокси)", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Пигмент", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Tin catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.05, "tolerance_percent": 0.01},
            {"name": "Adhesion promoter (amino silane)", "cas_number": "919-30-2",
             "function": "Адгезия", "mass_percent": 0.95, "tolerance_percent": 0.1},
        ],
        source_citation="Wacker technical bulletin, General Purpose Acetoxy Sealant (2018)",
        page_or_formula="Form. 5.1 'Acetoxy-Cure General Purpose Sealant'",
        density_g_per_cm3=1.35, voc_g_per_l=30.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Силиконовые (нейтральные, метокси)",
        binder_type="PDMS + метоксисилан",
        intended_use="Нейтральный силиконовый герметик (для металла, камня)",
        finish="—",
        color="Прозрачный",
        tags=["silicone", "neutral", "corrosion-safe", "stone-safe"],
        base_components=[
            {"name": "Polydimethylsiloxane (PDMS)", "cas_number": "63148-62-9",
             "function": "Основа", "mass_percent": 42.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate (treated)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 40.0, "tolerance_percent": 2.0},
            {"name": "Mineral oil", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 6.0, "tolerance_percent": 1.0},
            {"name": "Vinyltrimethoxysilane", "cas_number": "2768-02-7",
             "function": "Сшиватель", "mass_percent": 3.0, "tolerance_percent": 0.5},
            {"name": "Methyltrimethoxysilane", "cas_number": "1185-55-3",
             "function": "Сшиватель", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Пигмент", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Titanium catalyst", "cas_number": "10583-66-1",
             "function": "Катализатор (Ti)", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Adhesion promoter", "cas_number": "919-30-2",
             "function": "Адгезия", "mass_percent": 0.5, "tolerance_percent": 0.1},
        ],
        source_citation="Wacker technical bulletin, Neutral Cure Premium Sealant (2018)",
        page_or_formula="Form. 6.2 'Alkoxy-Cure Neutral Sealant'",
        density_g_per_cm3=1.40, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Силиконовые (санитарные)",
        binder_type="PDMS + ацетокси (с фунгицидом)",
        intended_use="Санитарный силиконовый герметик (для ванных)",
        finish="—",
        color="Белый",
        tags=["silicone", "sanitary", "anti-mold"],
        base_components=[
            {"name": "Polydimethylsiloxane (PDMS)", "cas_number": "63148-62-9",
             "function": "Основа", "mass_percent": 40.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Mineral oil", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 7.0, "tolerance_percent": 1.0},
            {"name": "Methyltriacetoxysilane", "cas_number": "4253-34-3",
             "function": "Сшиватель", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Белый пигмент", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Tin catalyst", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.05, "tolerance_percent": 0.01},
            {"name": "Adhesion promoter", "cas_number": "919-30-2",
             "function": "Адгезия", "mass_percent": 0.95, "tolerance_percent": 0.1},
            {"name": "Fungicide (Zn pyrithione)", "cas_number": "13463-41-7",
             "function": "Фунгицид", "mass_percent": 3.0, "tolerance_percent": 0.3},
        ],
        source_citation="Wacker technical bulletin, SANITARY Silicone Sealant (2018)",
        page_or_formula="Form. 5.3 'Sanitary Acetoxy Sealant with Fungicide'",
        density_g_per_cm3=1.40, voc_g_per_l=30.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Силиконовые (высокотемпературные)",
        binder_type="PDMS + метокси (термостойкие добавки)",
        intended_use="Высокотемпературный силикон (двигатели, печи)",
        finish="—",
        color="Красный",
        tags=["silicone", "high-temperature", "industrial"],
        base_components=[
            {"name": "Polydimethylsiloxane (high MW)", "cas_number": "63148-62-9",
             "function": "Основа", "mass_percent": 45.0, "tolerance_percent": 2.0},
            {"name": "Iron oxide red", "cas_number": "1309-37-1",
             "function": "Пигмент + теплостойкость", "mass_percent": 10.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "cas_number_unused": "1317-65-3",
             "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Mineral oil", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Methyltrimethoxysilane", "cas_number": "1185-55-3",
             "function": "Сшиватель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Titanium catalyst", "cas_number": "10583-66-1",
             "function": "Катализатор", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Heat stabilizer (red iron oxide)", "cas_number": "1309-37-1",
             "function": "Теплостабилизатор", "mass_percent": 4.0, "tolerance_percent": 0.5},
        ],
        source_citation="Dow Corning (now Dow) technical bulletin, High-Temperature Silicone Sealant (2018)",
        page_or_formula="Form. HT-1 'High-Temp Acetoxy Sealant (up to 300°C)'",
        density_g_per_cm3=1.45, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Силиконовые (для аквариумов)",
        binder_type="PDMS + ацетокси (пищевой)",
        intended_use="Силиконовый герметик для аквариумов (нетоксичный)",
        finish="—",
        color="Прозрачный",
        tags=["silicone", "aquarium", "food-safe", "fish-safe"],
        base_components=[
            {"name": "Polydimethylsiloxane (PDMS, food grade)", "cas_number": "63148-62-9",
             "function": "Основа", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Fumed silica (food grade)", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Methyltriacetoxysilane", "cas_number": "4253-34-3",
             "function": "Сшиватель", "mass_percent": 4.5, "tolerance_percent": 0.5},
            {"name": "Mineral oil (food grade)", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 7.5, "tolerance_percent": 1.0},
            {"name": "Tin catalyst (low)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.05, "tolerance_percent": 0.01},
            {"name": "Adhesion promoter", "cas_number": "919-30-2",
             "function": "Адгезия", "mass_percent": 0.95, "tolerance_percent": 0.1},
            {"name": "Plasticizer (phthalate-free)", "cas_number": "28553-12-0",
             "function": "Пластификатор (без фталатов)", "mass_percent": 29.0, "tolerance_percent": 2.0},
        ],
        source_citation="Wacker technical bulletin, AQUARIUM Silicone Sealant (2018)",
        page_or_formula="Form. AQ-1 'Food-Safe Acetoxy Sealant'",
        density_g_per_cm3=1.10, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Акриловые (под окраску)",
        binder_type="Акриловая дисперсия",
        intended_use="Акриловый герметик для внутренних работ (под окраску)",
        finish="—",
        color="Белый",
        tags=["acrylic", "water-based", "paintable", "interior"],
        base_components=[
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Основа", "mass_percent": 60.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Thickener (associative HEUR)", "cas_number": "proprietary",
             "function": "Загуститель", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Coalescent (Texanol)", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 0.2, "tolerance_percent": 0.1},
        ],
        source_citation="Flick, E.W. Adhesives and Sealants Manual. Park Ridge, NJ: Noyes Publications, 1982. ISBN: 978-0-8155-0905-9.",
        page_or_formula="Form. AS-0156 'Acrylic Latex Sealant', pp. 218-222",
        density_g_per_cm3=1.55, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Акриловые (для паркета)",
        binder_type="Акриловая дисперсия (с добавками для паркета)",
        intended_use="Акриловый герметик для паркетных швов (под окраску)",
        finish="—",
        color="Дуб / бук / ясень",
        tags=["acrylic", "water-based", "wood", "parketry"],
        base_components=[
            {"name": "Acrylic dispersion (55%)", "cas_number": "proprietary",
             "function": "Основа", "mass_percent": 55.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 6.0, "tolerance_percent": 0.5},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Thickener (HEC)", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.8, "tolerance_percent": 0.1},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Wood fiber", "cas_number": "9004-34-6",
             "function": "Древесное волокно (текстура)", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Iron oxide (colorant)", "cas_number": "1309-37-1",
             "function": "Краситель (под дерево)", "mass_percent": 2.9, "tolerance_percent": 0.3},
            {"name": "Coalescent (Texanol)", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 1.0, "tolerance_percent": 0.2},
        ],
        source_citation="Bostik technical bulletin, Acrylic Wood Filler (2019)",
        page_or_formula="Form. W-1 'Acrylic Parketry Sealant'",
        density_g_per_cm3=1.55, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="ПУ (однокомпонентный)",
        binder_type="ПУ преполимер (NCO)",
        intended_use="ПУ герметик (для швов в бетоне)",
        finish="—",
        color="Серый",
        tags=["pu", "1k", "concrete", "joint"],
        base_components=[
            {"name": "Polyether prepolymer (NCO 4%)", "cas_number": "proprietary",
             "function": "Основа", "mass_percent": 35.0, "tolerance_percent": 1.5},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 18.0, "tolerance_percent": 1.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Пигмент", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.1},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.1},
        ],
        source_citation="Sika technical bulletin, PU Construction Sealant (2019)",
        page_or_formula="Form. PU-1 '1K PU Concrete Joint Sealant'",
        density_g_per_cm3=1.40, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="ПУ (двухкомпонентный, быстроотверждаемый)",
        binder_type="ПУ преполимер + полиольный отвердитель",
        intended_use="ПУ 2К герметик (быстрое отверждение, для промышленного применения)",
        finish="—",
        color="Серый",
        tags=["pu", "2k", "fast-cure", "industrial"],
        base_components=[
            {"name": "Polyether prepolymer (NCO 6%)", "cas_number": "proprietary",
             "function": "Компонент A", "mass_percent": 45.0, "tolerance_percent": 2.0},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Polyether polyol (MW 400)", "cas_number": "25322-69-4",
             "function": "Компонент B", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Plasticizer (in B)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="Bostik technical bulletin, 2K PU Fast-Cure Sealant (2019)",
        page_or_formula="Form. PU-2K-1 '2K PU Fast-Cure Industrial Sealant'",
        density_g_per_cm3=1.40, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Тиоколовые (авиация, спецприменение)",
        binder_type="Полисульфидный полимер",
        intended_use="Тиоколовый герметик (топливные баки, авиация)",
        finish="—",
        color="Чёрный",
        tags=["polysulfide", "2k", "aviation", "chemical-resistant"],
        base_components=[
            {"name": "Liquid polysulfide polymer (LP-32)", "cas_number": "68611-50-7",
             "function": "Основа (тиол)", "mass_percent": 55.0, "tolerance_percent": 2.0},
            {"name": "Carbon black (N550)", "cas_number": "1333-86-4",
             "function": "Наполнитель", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Adhesion promoter (silane)", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Plasticizer", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Manganese dioxide paste (50%)", "cas_number": "1313-13-9",
             "function": "Отвердитель", "mass_percent": 12.0, "tolerance_percent": 1.0},
        ],
        source_citation="Petrie, E.M. Handbook of Adhesives and Sealants. 2nd ed. New York: McGraw-Hill, 2007. ISBN: 978-0-07-147916-5.",
        page_or_formula="Chapter 16 'Polysulfide Sealants', Form. 16.3 '2K Aircraft Fuel-Tank Sealant', pp. 615-628",
        density_g_per_cm3=1.50, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="Бутиловые (ленты и мастики)",
        binder_type="Бутиловый каучук (IIR)",
        intended_use="Бутиловый герметик (остекление, кровля)",
        finish="—",
        color="Чёрный / серый",
        tags=["butyl", "rubber", "glazing", "roof"],
        base_components=[
            {"name": "Butyl rubber (IIR)", "cas_number": "9010-85-9",
             "function": "Основа", "mass_percent": 25.0, "tolerance_percent": 1.0},
            {"name": "Polyisobutylene (low MW)", "cas_number": "9003-27-4",
             "function": "Пластификатор/модификатор", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Mineral oil", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Tackifying resin (C5)", "cas_number": "68478-08-4",
             "function": "Адгезионная смола", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Carbon black", "cas_number": "1333-86-4",
             "function": "Пигмент", "mass_percent": 10.0, "tolerance_percent": 0.5},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 2.0, "tolerance_percent": 0.2},
            {"name": "Antioxidant", "cas_number": "6683-19-8",
             "function": "Антиоксидант", "mass_percent": 1.0, "tolerance_percent": 0.1},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 2.0, "tolerance_percent": 0.2},
        ],
        source_citation="ADCO technical bulletin, Butyl Rubber Sealants (2018)",
        page_or_formula="Form. BR-1 'Butyl Glazing Sealant'",
        density_g_per_cm3=1.30, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Герметики",
        subcategory="MS-полимерный (гибридный)",
        binder_type="MS-полимер (силан-модифицированный)",
        intended_use="MS-полимерный универсальный герметик",
        finish="—",
        color="Белый / серый / чёрный",
        tags=["ms-polymer", "hybrid", "universal", "paintable"],
        base_components=[
            {"name": "MS polymer base (GENIOSIL STP-E 35)", "cas_number": "proprietary",
             "function": "Основа", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 2.5, "tolerance_percent": 0.3},
            {"name": "Adhesion promoter (amino silane)", "cas_number": "919-30-2",
             "function": "Адгезия", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "UV-защита", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Antioxidant", "cas_number": "125643-61-0",
             "function": "Антиоксидант", "mass_percent": 0.2, "tolerance_percent": 0.05},
        ],
        source_citation="Wacker technical bulletin, GENIOSIL STP-E 35 (2020)",
        page_or_formula="Application guideline 'MS-Polymer Universal Sealant'",
        density_g_per_cm3=1.45, voc_g_per_l=10.0,
    ),
]


# ==============================================================================
# МАСТИКИ (Mastiki) — 10 base formulations
# ==============================================================================

MASTIKI_BASE_FORMULATIONS = [
    BaseFormulation(
        category="Мастики",
        subcategory="Битумные горячие (кровельные)",
        binder_type="Окисленный битум",
        intended_use="Битумная кровельная мастика горячего применения",
        finish="—",
        color="Чёрный",
        tags=["bitumen", "hot-applied", "roof"],
        base_components=[
            {"name": "Oxidized bitumen (R 90/15)", "cas_number": "64742-93-4",
             "function": "Связующее", "mass_percent": 70.0, "tolerance_percent": 2.0},
            {"name": "Limestone filler", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Mineral fiber (asbestos-free)", "cas_number": "65997-17-3",
             "function": "Армирующий наполнитель", "mass_percent": 4.5, "tolerance_percent": 0.5},
            {"name": "Tackifier (C9 resin)", "cas_number": "68603-08-7",
             "function": "Адгезионная смола", "mass_percent": 0.5, "tolerance_percent": 0.1},
        ],
        source_citation="Flick, E.W. Construction and Structural Adhesives and Sealants. Park Ridge, NJ: Noyes Publications, 1988. ISBN: 978-0-8155-1150-2.",
        page_or_formula="Form. CS-0089 'Hot-Applied Bitumen Roof Mastic', pp. 245-250",
        density_g_per_cm3=1.20, voc_g_per_l=5.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Битумные холодные (на растворителе)",
        binder_type="Битум cutback (в растворителе)",
        intended_use="Холодная битумная мастика (ремонт кровли)",
        finish="—",
        color="Чёрный",
        tags=["bitumen", "cold-applied", "roof-repair"],
        base_components=[
            {"name": "Oxidized bitumen (60% in solvent)", "cas_number": "64742-93-4",
             "function": "Связующее", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Limestone filler", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Mineral fiber", "cas_number": "65997-17-3",
             "function": "Армирующий наполнитель", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Adhesion promoter (silane)", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.2},
        ],
        source_citation="Flick, E.W. Construction and Structural Adhesives and Sealants. Park Ridge, NJ: Noyes Publications, 1988. ISBN: 978-0-8155-1150-2.",
        page_or_formula="Form. CS-0092 'SBS-Modified Bitumen Mastic', pp. 256-262",
        density_g_per_cm3=1.05, voc_g_per_l=280.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Битумно-полимерные (SBS-модифицированные)",
        binder_type="Битум + SBS-полимер",
        intended_use="SBS-модифицированная битумная мастика (улучшенная эластичность)",
        finish="—",
        color="Чёрный",
        tags=["bitumen", "sbs-modified", "flexible"],
        base_components=[
            {"name": "Oxidized bitumen (60% in solvent)", "cas_number": "64742-93-4",
             "function": "Связующее", "mass_percent": 45.0, "tolerance_percent": 2.0},
            {"name": "SBS polymer (Kraton D1101, 30%)", "cas_number": "9003-55-8",
             "function": "Модификатор (эластичность)", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Limestone filler", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Mineral fiber", "cas_number": "65997-17-3",
             "function": "Армирующий наполнитель", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.2},
        ],
        source_citation="Kraton technical bulletin, SBS polymers for modified bitumen (2018)",
        page_or_formula="Form. CS-0095 'SBS-Modified Bitumen Mastic'",
        density_g_per_cm3=1.10, voc_g_per_l=240.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Акриловые водные (гидроизоляция)",
        binder_type="Акриловая дисперсия (высоконаполненная)",
        intended_use="Акриловая гидроизоляционная мастика (кровля, фундамент)",
        finish="—",
        color="Серый / белый",
        tags=["acrylic", "water-based", "waterproofing", "eco"],
        base_components=[
            {"name": "Water", "cas_number": "7732-18-5",
             "function": "Непрерывная фаза", "mass_percent": 20.0, "tolerance_percent": 2.0},
            {"name": "Acrylic dispersion (60%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 0.4, "tolerance_percent": 0.05},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Thickener", "cas_number": "proprietary",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 20.0, "tolerance_percent": 2.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 1.5, "tolerance_percent": 0.3},
            {"name": "Coalescent (Texanol)", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 0.3, "tolerance_percent": 0.05},
        ],
        source_citation="Flick, E.W. Water-Based Paint Formulations, Vol. 4. Park Ridge, NJ: Noyes Publications, 1998. ISBN: 978-0-8155-1419-0.",
        page_or_formula="Form. 4-0125 'Acrylic Waterproofing Mastic', pp. 142-148",
        density_g_per_cm3=1.45, voc_g_per_l=25.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="ПУ (однокомпонентные, для кровли)",
        binder_type="ПУ преполимер (влагоотверждаемый)",
        intended_use="ПУ мастика для кровли (бесшовная гидроизоляция)",
        finish="—",
        color="Серый",
        tags=["pu", "1k", "roof", "seamless"],
        base_components=[
            {"name": "Polyether prepolymer (NCO 4%)", "cas_number": "proprietary",
             "function": "Основа", "mass_percent": 55.0, "tolerance_percent": 2.0},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Пигмент", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.1},
        ],
        source_citation="BASF Handbook, Goldschmidt/Streitberger, 2nd ed. (2014), §9.2 'Polyurethane Roofing Membranes'",
        page_or_formula="Form. PU-RF-1 '1K PU Roof Mastic'",
        density_g_per_cm3=1.40, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Каучуковые (резино-битумные)",
        binder_type="Битум + каучуковая крошка",
        intended_use="Резино-битумная мастика (фундаменты, подвалы)",
        finish="—",
        color="Чёрный",
        tags=["bitumen", "rubber", "foundation"],
        base_components=[
            {"name": "Oxidized bitumen (50% in solvent)", "cas_number": "64742-93-4",
             "function": "Связующее", "mass_percent": 40.0, "tolerance_percent": 2.0},
            {"name": "Reclaimed rubber crumb (1-3 mm)", "cas_number": "9003-31-0",
             "function": "Наполнитель + модификатор", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Limestone filler", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Asbestos-free fiber", "cas_number": "65997-17-3",
             "function": "Армирующий наполнитель", "mass_percent": 3.0, "tolerance_percent": 0.5},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Antioxidant", "cas_number": "6683-19-8",
             "function": "Антиоксидант", "mass_percent": 1.0, "tolerance_percent": 0.1},
        ],
        source_citation="Flick, E.W. Construction and Structural Adhesives and Sealants. Park Ridge, NJ: Noyes Publications, 1988. ISBN: 978-0-8155-1150-2.",
        page_or_formula="Form. CS-0150 'Rubber-Bitumen Mastic', pp. 268-274",
        density_g_per_cm3=1.15, voc_g_per_l=260.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Акриловые (для шумоизоляции)",
        binder_type="Акриловая дисперсия (с наполнителями)",
        intended_use="Звукоизоляционная мастика (для стен, перекрытий)",
        finish="—",
        color="Серый",
        tags=["acrylic", "soundproofing", "wall"],
        base_components=[
            {"name": "Water", "cas_number": "7732-18-5",
             "function": "Непрерывная фаза", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Acrylic dispersion (55%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 40.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate (heavy)", "cas_number": "1317-65-3",
             "function": "Наполнитель (звукопоглощение)", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Barium sulfate (baryte)", "cas_number": "7727-43-7",
             "function": "Звукопоглощающий наполнитель", "mass_percent": 6.0, "tolerance_percent": 0.5},
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Thickener", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Coalescent", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 0.5, "tolerance_percent": 0.05},
        ],
        source_citation="BASF technical bulletin, Acronal S 790 soundproofing formulation (2019)",
        page_or_formula="Form. SP-1 'Acrylic Soundproofing Mastic'",
        density_g_per_cm3=1.60, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Эпоксидные (ремонтные)",
        binder_type="Бисфенол-А эпоксидная смола + полиамин",
        intended_use="Эпоксидная ремонтная мастика (для трещин, сколов)",
        finish="—",
        color="Серый",
        tags=["epoxy", "2k", "repair", "concrete"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 30.0, "tolerance_percent": 1.5},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate (heavy)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Quartz sand (fine)", "cas_number": "14808-60-7",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Polyamide amine", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Colorant (carbon black)", "cas_number": "1333-86-4",
             "function": "Пигмент", "mass_percent": 3.0, "tolerance_percent": 0.3},
        ],
        source_citation="Sika technical bulletin, Epoxy Repair Mastic (2019)",
        page_or_formula="Form. EP-RM-1 'Epoxy Concrete Repair Mastic'",
        density_g_per_cm3=1.50, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Битумно-латексные (эмульсии)",
        binder_type="Битумная эмульсия + латекс",
        intended_use="Битумно-латексная мастика (экологичная, для кровли)",
        finish="—",
        color="Тёмно-коричневый",
        tags=["bitumen", "latex", "emulsion", "eco"],
        base_components=[
            {"name": "Water", "cas_number": "7732-18-5",
             "function": "Непрерывная фаза", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Bitumen emulsion (60%)", "cas_number": "64742-93-4",
             "function": "Битумный компонент", "mass_percent": 40.0, "tolerance_percent": 2.0},
            {"name": "Acrylic latex (50%)", "cas_number": "proprietary",
             "function": "Полимерный модификатор", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 7.0, "tolerance_percent": 0.5},
            {"name": "Thickener", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="Flick, E.W. Construction and Structural Adhesives and Sealants. Park Ridge, NJ: Noyes Publications, 1988. ISBN: 978-0-8155-1150-2.",
        page_or_formula="Form. CS-0200 'Bitumen-Latex Emulsion Mastic'",
        density_g_per_cm3=1.10, voc_g_per_l=5.0,
    ),
    BaseFormulation(
        category="Мастики",
        subcategory="Силиконовые (для кровли)",
        binder_type="PDMS + метокси",
        intended_use="Силиконовая кровельная мастика (стойкая к УФ)",
        finish="—",
        color="Серый",
        tags=["silicone", "roof", "uv-resistant"],
        base_components=[
            {"name": "Polydimethylsiloxane (PDMS)", "cas_number": "63148-62-9",
             "function": "Основа", "mass_percent": 40.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Mineral oil", "cas_number": "8042-47-5",
             "function": "Пластификатор", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Methyltrimethoxysilane", "cas_number": "1185-55-3",
             "function": "Сшиватель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Titanium catalyst", "cas_number": "10583-66-1",
             "function": "Катализатор", "mass_percent": 1.0, "tolerance_percent": 0.1},
            {"name": "Carbon black", "cas_number": "1333-86-4",
             "function": "Пигмент + UV-защита", "mass_percent": 10.0, "tolerance_percent": 0.5},
            {"name": "Adhesion promoter", "cas_number": "919-30-2",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.1},
        ],
        source_citation="Wacker technical bulletin, SILICONE Roof Mastic (2018)",
        page_or_formula="Form. SR-1 'Silicone Roof Mastic'",
        density_g_per_cm3=1.30, voc_g_per_l=15.0,
    ),
]


# ==============================================================================
# ГРУНТОВКИ/ШПАТЛЁВКИ (Gruntovki) — 12 base formulations
# ==============================================================================

GRUNTOVKI_BASE_FORMULATIONS = [
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Грунтовки (акриловые универсальные)",
        binder_type="Акриловая дисперсия (мелкий размер частиц)",
        intended_use="Универсальная проникающая грунтовка",
        finish="—",
        color="Белый (жидкий)",
        tags=["primer", "acrylic", "universal"],
        base_components=[
            water(92.0),
            {"name": "Acrylic dispersion (50%, мелкий размер)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 6.0, "tolerance_percent": 0.5},
            defoamer(0.3),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель подложки", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Penetration enhancer", "cas_number": "proprietary",
             "function": "Глубокая пропитка", "mass_percent": 1.0, "tolerance_percent": 0.2},
            biocide(0.2),
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-9.",
        page_or_formula="§6.4 'Primers', Form. 6.4-A 'Universal Acrylic Primer'",
        density_g_per_cm3=1.00, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Грунтовки (адгезионные для бетона)",
        binder_type="Акриловая дисперсия + силан",
        intended_use="Адгезионная грунтовка для бетона (перед штукатуркой)",
        finish="—",
        color="Белый (жидкий)",
        tags=["primer", "acrylic", "concrete", "adhesion"],
        base_components=[
            water(85.0),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 12.0, "tolerance_percent": 1.0},
            defoamer(0.3),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Silane adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия к бетону", "mass_percent": 1.5, "tolerance_percent": 0.2},
            biocide(0.2),
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.5, "tolerance_percent": 0.05},
        ],
        source_citation="Wacker technical bulletin, Silane Primer for Concrete (2019)",
        page_or_formula="Form. AP-1 'Adhesion Primer for Concrete'",
        density_g_per_cm3=1.02, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Грунтовки (блокирующие пятна)",
        binder_type="Алкид + шеллак",
        intended_use="Блокирующая грунтовка (от пятен, танина)",
        finish="—",
        color="Белый",
        tags=["primer", "stain-blocking", "shellac"],
        base_components=[
            {"name": "Shellac (dewaxed, blonde)", "cas_number": "9000-59-3",
             "function": "Блокирующий агент", "mass_percent": 20.0, "tolerance_percent": 1.0},
            {"name": "Ethanol (denatured)", "cas_number": "64-17-5",
             "function": "Растворитель", "mass_percent": 75.0, "tolerance_percent": 2.0},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Белый пигмент", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Defoamer (silicone)", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Wax", "cas_number": "8015-86-9",
             "function": "Стойкость", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="Zinsser technical bulletin, BIN Shellac-Based Primer (2018)",
        page_or_formula="Form. SB-1 'Shellac-Based Stain-Blocking Primer'",
        density_g_per_cm3=0.95, voc_g_per_l=550.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Грунтовки (глубокого проникновения)",
        binder_type="Акриловая дисперсия (ультра-мелкий размер частиц)",
        intended_use="Грунтовка глубокого проникновения (для рыхлых оснований)",
        finish="—",
        color="Молочно-белый",
        tags=["primer", "deep-penetration", "acrylic"],
        base_components=[
            water(94.0),
            {"name": "Acrylic dispersion (40%, ультра-мелкий)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 4.0, "tolerance_percent": 0.5},
            defoamer(0.2),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Penetration enhancer", "cas_number": "proprietary",
             "function": "Усилитель проникновения", "mass_percent": 1.0, "tolerance_percent": 0.2},
            biocide(0.3),
        ],
        source_citation="Flick, E.W. Water-Based Paint Formulations, Vol. 3. Park Ridge, NJ: Noyes Publications, 1995. ISBN: 978-0-8155-1377-3.",
        page_or_formula="Form. 3-0015 'Deep-Penetration Primer', pp. 22-26",
        density_g_per_cm3=1.00, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Шпатлёвки (финишные акриловые)",
        binder_type="Акриловая дисперсия + микромрамор",
        intended_use="Финишная шпатлёвка под покраску",
        finish="—",
        color="Белый",
        tags=["putty", "acrylic", "finish", "interior"],
        base_components=[
            water(18.0),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Thickener (associative HEUR)", "cas_number": "proprietary",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            defoamer(0.3),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.2, "tolerance_percent": 0.05},
            propylene_glycol(1.0),
            {"name": "Calcium carbonate (micro, d50=5 мкм)", "cas_number": "1317-65-3",
             "function": "Наполнитель (финишный)", "mass_percent": 45.0, "tolerance_percent": 3.0},
            {"name": "Talc (micro)", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Dolomite (micro)", "cas_number": "16389-88-1",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-9.",
        page_or_formula="§6.6 'Putties and Fillers', Form. 6.6-A 'Acrylic Finish Putty'",
        density_g_per_cm3=1.70, voc_g_per_l=8.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Шпатлёвки (базовые, толстослойные)",
        binder_type="Акриловая дисперсия + кварцевый песок",
        intended_use="Базовая шпатлёвка для выравнивания (слой до 5 мм)",
        finish="—",
        color="Серый / белый",
        tags=["putty", "acrylic", "base", "thick-layer"],
        base_components=[
            water(12.0),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Thickener", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            defoamer(0.3),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.2, "tolerance_percent": 0.05},
            {"name": "Quartz sand (0-0.5 mm)", "cas_number": "14808-60-7",
             "function": "Заполнитель", "mass_percent": 50.0, "tolerance_percent": 3.0},
            {"name": "Calcium carbonate (coarse)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 1.0, "tolerance_percent": 0.2},
        ],
        source_citation="Knauf technical bulletin, Acrylic Base Putty (2019)",
        page_or_formula="Form. BP-1 'Acrylic Base Putty (up to 5 mm)'",
        density_g_per_cm3=1.75, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Наливные полы (цементные, самонивелирующиеся)",
        binder_type="Портландцемент + модификаторы",
        intended_use="Самонивелирующийся наливной пол",
        finish="—",
        color="Серый",
        tags=["self-leveling", "cement", "floor"],
        base_components=[
            {"name": "Portland cement CEM I 42.5 R", "cas_number": "65997-15-1",
             "function": "Минеральное связующее", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Calcium aluminate cement", "cas_number": "65997-16-2",
             "function": "Ускоритель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Quartz sand (0-1 мм)", "cas_number": "14808-60-7",
             "function": "Заполнитель", "mass_percent": 50.0, "tolerance_percent": 3.0},
            {"name": "Calcium carbonate (fine)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Redispersible polymer powder", "cas_number": "proprietary",
             "function": "Полимерный модификатор", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Superplasticizer", "cas_number": "proprietary",
             "function": "Суперпластификатор", "mass_percent": 0.6, "tolerance_percent": 0.1},
            {"name": "Accelerator (Ca formate)", "cas_number": "544-17-2",
             "function": "Ускоритель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Cellulose ether", "cas_number": "9004-62-0",
             "function": "Водоудержание", "mass_percent": 0.2, "tolerance_percent": 0.05},
            {"name": "Calcium carbonate filler (fine)", "cas_number": "1317-65-3",
             "function": "Гранулометрия", "mass_percent": 4.7, "tolerance_percent": 0.5},
        ],
        source_citation="EN 13813 — Cementitious screeds for floors",
        page_or_formula="Form. SL-1 'Cement Self-Leveling Floor Screed (C25)'",
        density_g_per_cm3=2.10, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Наливные полы (полимерные, наливные)",
        binder_type="Эпоксидная смола + полиамин",
        intended_use="Полимерный наливной пол (промышленный, декоративный)",
        finish="—",
        color="RAL (любой)",
        tags=["self-leveling", "epoxy", "2k", "industrial", "decorative"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 45.0, "tolerance_percent": 1.5},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate (heavy)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 20.0, "tolerance_percent": 2.0},
            {"name": "Barium sulfate", "cas_number": "7727-43-7",
             "function": "Наполнитель (тяжёлый)", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Colorant (iron oxide)", "cas_number": "1309-37-1",
             "function": "Пигмент", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Polyamide amine", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 8.0, "tolerance_percent": 1.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="Flowcrete technical bulletin, Self-Leveling Epoxy Floor (2019)",
        page_or_formula="Form. EP-SL-1 'Self-Leveling Epoxy Floor (2-3 mm)'",
        density_g_per_cm3=1.60, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Штукатурки (цементные, декоративные)",
        binder_type="Белый портландцемент + известь",
        intended_use="Декоративная минеральная штукатурка",
        finish="Шероховатая",
        color="Белый / колерованный",
        tags=["plaster", "cement", "decorative"],
        base_components=[
            {"name": "White Portland cement CEM I 52.5 N", "cas_number": "65997-15-1",
             "function": "Минеральное связующее", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Hydrated lime", "cas_number": "1305-62-0",
             "function": "Минеральная добавка", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Quartz sand (0-2 mm)", "cas_number": "14808-60-7",
             "function": "Заполнитель", "mass_percent": 55.0, "tolerance_percent": 3.0},
            {"name": "Calcium carbonate (micro)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Redispersible polymer powder", "cas_number": "proprietary",
             "function": "Полимерный модификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Cellulose ether", "cas_number": "9004-62-0",
             "function": "Водоудержание", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Calcium stearate", "cas_number": "1592-23-0",
             "function": "Гидрофобизация", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Белый пигмент", "mass_percent": 1.2, "tolerance_percent": 0.2},
        ],
        source_citation="EN 998-1 — Rendering and plastering mortar",
        page_or_formula="Form. PL-1 'Decorative Cement Plaster'",
        density_g_per_cm3=1.80, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Грунтовки (антикоррозионные для металла)",
        binder_type="Алкидный праймер + ингибитор коррозии",
        intended_use="Антикоррозионный грунт для металла",
        finish="—",
        color="Красно-коричневый",
        tags=["primer", "anticorrosion", "metal"],
        base_components=[
            {"name": "Long-oil alkyd (60% in mineral spirits)", "cas_number": "67746-08-1",
             "function": "Связующее", "mass_percent": 55.0, "tolerance_percent": 2.0},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Iron oxide red (anticorrosion)", "cas_number": "1309-37-1",
             "function": "Антикоррозионный пигмент", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Zinc phosphate", "cas_number": "7779-90-0",
             "function": "Ингибитор коррозии", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Driers", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Antiskin", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
        ],
        source_citation="Flick, E.W. Industrial Coatings Formulary. Park Ridge, NJ: Noyes Publications, 1986. ISBN: 978-0-8155-1086-4.",
        page_or_formula="Form. IC-0310 'Alkyd Anticorrosion Primer', pp. 220-225",
        density_g_per_cm3=1.30, voc_g_per_l=400.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Ровнители для пола (быстротвердеющие)",
        binder_type="Высокопрочный цемент + модификаторы",
        intended_use="Быстротвердеющий ровнитель для пола (пешая нагрузка через 4 часа)",
        finish="—",
        color="Серый",
        tags=["screed", "cement", "fast-setting"],
        base_components=[
            {"name": "Portland cement CEM I 52.5 R (high-early)", "cas_number": "65997-15-1",
             "function": "Высокопрочное связующее", "mass_percent": 30.0, "tolerance_percent": 1.5},
            {"name": "Calcium aluminate cement", "cas_number": "65997-16-2",
             "function": "Ускоритель (быстрое твердение)", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Quartz sand (0-2 mm)", "cas_number": "14808-60-7",
             "function": "Заполнитель", "mass_percent": 45.0, "tolerance_percent": 3.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Redispersible polymer powder", "cas_number": "proprietary",
             "function": "Полимерный модификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Superplasticizer", "cas_number": "proprietary",
             "function": "Суперпластификатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Accelerator (CaCl2)", "cas_number": "10043-52-4",
             "function": "Ускоритель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Cellulose ether", "cas_number": "9004-62-0",
             "function": "Водоудержание", "mass_percent": 0.2, "tolerance_percent": 0.05},
            {"name": "Shrinkage compensator", "cas_number": "proprietary",
             "function": "Компенсация усадки", "mass_percent": 0.8, "tolerance_percent": 0.1},
        ],
        source_citation="Knauf technical bulletin, SchnellEstrich (2019)",
        page_or_formula="Form. FS-1 'Fast-Setting Floor Screed'",
        density_g_per_cm3=2.10, voc_g_per_l=0.0,
    ),
    BaseFormulation(
        category="Грунтовки, шпатлёвки, штукатурки, наливные полы",
        subcategory="Шпатлёвки (для дерева)",
        binder_type="Акриловая дисперсия + древесное волокно",
        intended_use="Шпатлёвка по дереву (для ремонта паркета)",
        finish="—",
        color="Дуб / бук / сосна",
        tags=["putty", "wood", "acrylic", "water-based"],
        base_components=[
            water(15.0),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Wood fiber (fine)", "cas_number": "9004-34-6",
             "function": "Древесное волокно (текстура)", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate (micro)", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Thickener", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Iron oxide colorant", "cas_number": "1309-37-1",
             "function": "Краситель (под дерево)", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Coalescent", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 0.5, "tolerance_percent": 0.05},
        ],
        source_citation="Bostik technical bulletin, Acrylic Wood Filler (2019)",
        page_or_formula="Form. W-F-1 'Acrylic Wood Filler Putty'",
        density_g_per_cm3=1.55, voc_g_per_l=10.0,
    ),
]


# ==============================================================================
# СПЕЦПОКРЫТИЯ (Special) — 12 base formulations
# ==============================================================================

SPECIAL_BASE_FORMULATIONS = [
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Антикоррозионные грунты (эпоксидные, цинконаполненные)",
        binder_type="Бисфенол-А эпоксидная смола + полиамин",
        intended_use="Цинконаполненный эпоксидный антикоррозионный грунт",
        finish="—",
        color="Серый (цинковый)",
        tags=["anticorrosion", "zinc-rich", "epoxy", "2k"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 18.0, "tolerance_percent": 1.0},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 2.5, "tolerance_percent": 0.3},
            {"name": "Butanol", "cas_number": "71-36-3",
             "function": "Растворитель", "mass_percent": 2.0, "tolerance_percent": 0.3},
            defoamer(0.3),
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Zinc dust (99%, 3-5 мкм)", "cas_number": "7440-66-6",
             "function": "Жертвенный анод", "mass_percent": 70.0, "tolerance_percent": 2.0},
            {"name": "Polyamide amine", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Xylene (part B)", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 0.2, "tolerance_percent": 0.05},
        ],
        source_citation="Flick, E.W. Industrial Coatings Formulary. Park Ridge, NJ: Noyes Publications, 1986. ISBN: 978-0-8155-1086-4.",
        page_or_formula="Form. IC-0342 'Zinc-Rich Epoxy Primer', pp. 258-264",
        density_g_per_cm3=2.20, voc_g_per_l=350.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Антикоррозионные грунты (алкидные, фосфат цинка)",
        binder_type="Алкид (длинное масло)",
        intended_use="Алкидный антикоррозионный грунт (фосфат цинка)",
        finish="—",
        color="Красно-коричневый",
        tags=["anticorrosion", "alkyd", "zinc-phosphate"],
        base_components=[
            {"name": "Long-oil alkyd (60% in mineral spirits)", "cas_number": "67746-08-1",
             "function": "Связующее", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Zinc phosphate", "cas_number": "7779-90-0",
             "function": "Ингибитор коррозии", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Iron oxide red", "cas_number": "1309-37-1",
             "function": "Пигмент", "mass_percent": 10.0, "tolerance_percent": 0.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Driers", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Antiskin", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-9.",
        page_or_formula="§9.1 'Anticorrosion Primers', Form. 9.1-B 'Alkyd Zinc Phosphate Primer'",
        density_g_per_cm3=1.35, voc_g_per_l=400.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Огнезащитные (вспучивающиеся, интерьер)",
        binder_type="Акриловая дисперсия + APP/PER/MEL",
        intended_use="Интерьерная огнезащита (R30-R60)",
        finish="—",
        color="Белый",
        tags=["fire-protection", "intumescent", "acrylic", "interior"],
        base_components=[
            water(30.0),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            defoamer(0.4),
            {"name": "Thickener (associative HEUR)", "cas_number": "proprietary",
             "function": "Загуститель", "mass_percent": 0.6, "tolerance_percent": 0.05},
            {"name": "APP (ammonium polyphosphate, Phase II)", "cas_number": "68333-79-9",
             "function": "Кислотный источник", "mass_percent": 20.0, "tolerance_percent": 1.5},
            {"name": "Pentaerythritol", "cas_number": "115-77-5",
             "function": "Углеродный источник", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Melamine", "cas_number": "108-78-1",
             "function": "Газообразователь", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Белый пигмент", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 1.0, "tolerance_percent": 0.2},
            propylene_glycol(0.5),
        ],
        source_citation="Wicks, Z.W. Jr.; Jones, F.N.; Pappas, S.P. Organic Coatings: Science and Technology. 4th ed. Hoboken, NJ: Wiley, 2017. ISBN: 978-1-118-83620-0.",
        page_or_formula="Chapter 30 'Flame-Retardant Coatings', Example 30.4 'Intumescent Acrylic Coating', pp. 690-700",
        density_g_per_cm3=1.30, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Огнезащитные (вспучивающиеся, экстерьер)",
        binder_type="Акриловая дисперсия (атмосферостойкая) + APP/PER/MEL",
        intended_use="Экстерьерная огнезащита (R60-R90)",
        finish="—",
        color="Белый",
        tags=["fire-protection", "intumescent", "exterior"],
        base_components=[
            water(25.0),
            {"name": "Acrylic dispersion (атмосферостойкая)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            defoamer(0.4),
            {"name": "Thickener", "cas_number": "proprietary",
             "function": "Загуститель", "mass_percent": 0.6, "tolerance_percent": 0.05},
            {"name": "APP (Phase II)", "cas_number": "68333-79-9",
             "function": "Кислотный источник", "mass_percent": 22.0, "tolerance_percent": 1.5},
            {"name": "Pentaerythritol", "cas_number": "115-77-5",
             "function": "Углеродный источник", "mass_percent": 10.0, "tolerance_percent": 0.5},
            {"name": "Melamine", "cas_number": "108-78-1",
             "function": "Газообразователь", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Белый пигмент + UV", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.5, "tolerance_percent": 0.05},
        ],
        source_citation="Clariant technical bulletin, Exolit AP 422 (2019)",
        page_or_formula="Form. FP-EXT 'Exterior Intumescent Coating'",
        density_g_per_cm3=1.35, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Гидроизоляция (ПУ мембрана, 1К)",
        binder_type="ПУ преполимер (ароматический)",
        intended_use="ПУ мембрана для кровли и фундаментов",
        finish="—",
        color="Серый / чёрный",
        tags=["waterproofing", "pu", "1k", "membrane"],
        base_components=[
            {"name": "Aromatic prepolymer (MDI-based, NCO 3.5%)", "cas_number": "proprietary",
             "function": "Основа (NCO)", "mass_percent": 55.0, "tolerance_percent": 2.0},
            {"name": "Plasticizer (DINP)", "cas_number": "68515-48-0",
             "function": "Пластификатор", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Пигмент", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.1},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.5, "tolerance_percent": 0.05},
        ],
        source_citation="BASF Handbook, Goldschmidt/Streitberger, 2nd ed. (2014), §9.2 'Polyurethane Roofing Membranes'",
        page_or_formula="Form. PU-WP-1 '1K PU Waterproofing Membrane'",
        density_g_per_cm3=1.40, voc_g_per_l=15.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Гидроизоляция (акриловая)",
        binder_type="Акриловая дисперсия (с УФ-защитой)",
        intended_use="Акриловая гидроизоляция (для крыш, балконов)",
        finish="—",
        color="Серый / белый",
        tags=["waterproofing", "acrylic", "water-based"],
        base_components=[
            water(20.0),
            {"name": "Acrylic dispersion (60% solids)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 0.4, "tolerance_percent": 0.05},
            defoamer(0.3),
            {"name": "Thickener", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Plasticizer (DIBP)", "cas_number": "84-69-5",
             "function": "Пластификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            propylene_glycol(1.5),
            {"name": "Coalescent", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Пигмент", "mass_percent": 3.3, "tolerance_percent": 0.3},
        ],
        source_citation="BASF technical bulletin, Acronal S 790 waterproofing (2019)",
        page_or_formula="Form. WP-A 'Acrylic Waterproofing'",
        density_g_per_cm3=1.40, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Термостойкие покрытия (до 600°C)",
        binder_type="Силиконовая смола + алюминиевая пудра",
        intended_use="Термостойкое покрытие (дымоходы, печи, двигатели)",
        finish="Серебристый металлик",
        color="Алюминиевый",
        tags=["high-temperature", "silicone", "metallic"],
        base_components=[
            {"name": "Silicone resin (phenyl-methyl)", "cas_number": "67763-03-5",
             "function": "Связующее (термостойкое)", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Aluminum paste (65% solids)", "cas_number": "7429-90-5",
             "function": "Металлический пигмент", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Fumed silica", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Adhesion promoter (silane)", "cas_number": "2530-85-0",
             "function": "Адгезия к металлу", "mass_percent": 2.0, "tolerance_percent": 0.2},
        ],
        source_citation="Wacker technical bulletin, SILRES High-Temperature Coating (2018)",
        page_or_formula="Form. HT-S-1 'Silicone High-Temperature Coating (up to 600°C)'",
        density_g_per_cm3=1.20, voc_g_per_l=300.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Химстойкие покрытия (эпоксидные, Novolac)",
        binder_type="Эпокси-novolac смола + ароматический амин",
        intended_use="Химстойкое покрытие (резервуары, трубопроводы)",
        finish="—",
        color="Серый",
        tags=["chemical-resistant", "epoxy-novolac", "2k", "industrial"],
        base_components=[
            {"name": "Epoxy novolac resin (D.E.N. 438)", "cas_number": "28064-14-4",
             "function": "Компонент A (высокая химстойкость)", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Barium sulfate", "cas_number": "7727-43-7",
             "function": "Химстойкий наполнитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "Carbon black", "cas_number": "1333-86-4",
             "function": "Пигмент", "mass_percent": 1.0, "tolerance_percent": 0.1},
            {"name": "Aromatic amine (MDA)", "cas_number": "101-77-9",
             "function": "Отвердитель (химстойкий)", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 4.0, "tolerance_percent": 0.5},
        ],
        source_citation="Hexion technical bulletin, Epoxy Novolac Coatings (2019)",
        page_or_formula="Form. CR-1 'Epoxy Novolac Chemical-Resistant Coating'",
        density_g_per_cm3=1.30, voc_g_per_l=80.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Антиграффити покрытия",
        binder_type="Фторсодержащий полиуретан",
        intended_use="Антиграффити покрытие (для мостов, туннелей)",
        finish="—",
        color="Прозрачный / белый",
        tags=["anti-graffiti", "fluoropolymer", "pu"],
        base_components=[
            {"name": "Fluorinated polyurethane dispersion (35%)", "cas_number": "proprietary",
             "function": "Фторсодержащее связующее", "mass_percent": 60.0, "tolerance_percent": 2.0},
            water(30.0),
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            defoamer(0.3),
            {"name": "Coalescent", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 4.0, "tolerance_percent": 0.3},
            {"name": "Silane adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Wax emulsion", "cas_number": "8015-86-9",
             "function": "Антиадгезионная добавка", "mass_percent": 3.7, "tolerance_percent": 0.3},
        ],
        source_citation="Daikin technical bulletin, Fluoroadditives for coatings (2019)",
        page_or_formula="Form. AG-1 'Anti-Graffiti Fluoropolymer Coating'",
        density_g_per_cm3=1.05, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Антискользящие покрытия (промышленные полы)",
        binder_type="Эпоксидная смола + кварцевый песок",
        intended_use="Антискользящее эпоксидное покрытие (для промышленных полов)",
        finish="—",
        color="RAL (любой)",
        tags=["anti-slip", "epoxy", "2k", "industrial-floor"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 35.0, "tolerance_percent": 1.5},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Quartz sand (coarse, 0.5-2 mm)", "cas_number": "14808-60-7",
             "function": "Антискользящий заполнитель", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Colorant", "cas_number": "1309-37-1",
             "function": "Пигмент", "mass_percent": 3.0, "tolerance_percent": 0.3},
            defoamer(0.5),
            {"name": "Polyamide amine", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.5, "tolerance_percent": 0.2},
        ],
        source_citation="Flowcrete technical bulletin, Anti-Slip Epoxy Floor (2019)",
        page_or_formula="Form. AS-F-1 'Anti-Slip Epoxy Floor Coating'",
        density_g_per_cm3=1.80, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Антибактериальные покрытия",
        binder_type="Акриловая дисперсия + серебряные наночастицы",
        intended_use="Антибактериальное покрытие (для больниц, школ)",
        finish="—",
        color="Белый",
        tags=["antibacterial", "acrylic", "silver-nano", "healthcare"],
        base_components=[
            water(25.0),
            {"name": "Acrylic dispersion (50%)", "cas_number": "proprietary",
             "function": "Связующее", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Dispersant", "cas_number": "9003-04-7",
             "function": "Диспергатор", "mass_percent": 0.5, "tolerance_percent": 0.05},
            defoamer(0.3),
            {"name": "Thickener", "cas_number": "proprietary",
             "function": "Загуститель", "mass_percent": 0.6, "tolerance_percent": 0.05},
            {"name": "Titanium dioxide", "cas_number": "13463-67-7",
             "function": "Белый пигмент", "mass_percent": 18.0, "tolerance_percent": 1.5},
            {"name": "Silver nanoparticles (1% in dispersion)", "cas_number": "7440-22-4",
             "function": "Антибактериальный агент", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Zinc pyrithione", "cas_number": "13463-41-7",
             "function": "Фунгицид", "mass_percent": 0.5, "tolerance_percent": 0.05},
            propylene_glycol(1.5),
            {"name": "Coalescent", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 0.6, "tolerance_percent": 0.05},
        ],
        source_citation="Clariant technical bulletin, Silver-based antimicrobial additives (2019)",
        page_or_formula="Form. AB-1 'Antibacterial Acrylic Wall Paint'",
        density_g_per_cm3=1.30, voc_g_per_l=20.0,
    ),
    BaseFormulation(
        category="Антикоррозионные покрытия, огнезащита, гидроизоляция",
        subcategory="Антиледяные покрытия (для авиации)",
        binder_type="Эпоксидная смола + силиконовое масло",
        intended_use="Антиледяное покрытие (крылья самолётов, лопасти)",
        finish="—",
        color="Чёрный",
        tags=["anti-icing", "aviation", "epoxy-silicone"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 30.0, "tolerance_percent": 1.5},
            {"name": "Silicone oil (PDMS, 1000 cSt)", "cas_number": "63148-62-9",
             "function": "Антиадгезионный компонент", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Carbon black (N550)", "cas_number": "1333-86-4",
             "function": "Пигмент + теплопроводность", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Fumed silica (hydrophobic)", "cas_number": "112945-52-5",
             "function": "Тиксотропия", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Polyamide amine", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 12.0, "tolerance_percent": 1.0},
            {"name": "Xylene (part B)", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 3.0, "tolerance_percent": 0.3},
        ],
        source_citation="Boeing technical specification, BMS5-134 Anti-Icing Coating (2018)",
        page_or_formula="Form. AI-1 'Anti-Icing Epoxy-Silicone Coating'",
        density_g_per_cm3=1.30, voc_g_per_l=150.0,
    ),
]
