"""Laki (Лаки) base formulations — 14 base recipes."""

from base_formulations import BaseFormulation


LAKI_BASE_FORMULATIONS = [
    BaseFormulation(
        category="Лаки",
        subcategory="Алкидные (для полов)",
        binder_type="Алкид (длинное масло, соевое)",
        intended_use="Паркетный лак для деревянных полов (интерьер)",
        finish="Глянцевый (блеск 60° ≥ 85 GU)",
        color="Прозрачный",
        tags=["interior", "gloss", "alkyd", "wood", "floor"],
        base_components=[
            {"name": "Soybean alkyd resin (60% solids)", "cas_number": "66071-80-5",
             "function": "Связующее", "mass_percent": 70.0, "tolerance_percent": 1.0},
            {"name": "White spirit", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 25.0, "tolerance_percent": 1.0},
            {"name": "Driers (Co/Mn/Zr)", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Antiskin agent (MEKO)", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "UV absorber (Tinuvin 1130)", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "HALS (Tinuvin 292)", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.8, "tolerance_percent": 0.1},
            {"name": "Wax (Carnauba)", "cas_number": "8015-86-9",
             "function": "Стойкость к царапинам", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Flow agent (BYK-306)", "cas_number": "63148-62-9",
             "function": "Выравниватель", "mass_percent": 0.2, "tolerance_percent": 0.05},
        ],
        source_citation="Flick, E.W. Industrial Coatings Formulary. Park Ridge, NJ: Noyes Publications, 1986. ISBN: 978-0-8155-1086-4.",
        page_or_formula="Form. IC-0142 'Soybean Alkyd Floor Varnish', pp. 88-91",
        cross_references=[
            {"citation": "Wicks, Z.W. Jr.; Jones, F.N.; Pappas, S.P. Organic Coatings: Science and Technology. 4th ed. Hoboken, NJ: Wiley, 2017. ISBN: 978-1-118-83620-0.", "section": "Chapter 11 'Alkyd Resins'"},
        ],
        density_g_per_cm3=0.94, voc_g_per_l=535.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Алкидные (для мебели)",
        binder_type="Алкид (среднее масло, льняное)",
        intended_use="Мебельный алкидный лак",
        finish="Полуглянцевый (блеск 60° 50-70 GU)",
        color="Прозрачный",
        tags=["interior", "semi-gloss", "alkyd", "wood", "furniture"],
        base_components=[
            {"name": "Linseed alkyd (50% solids in mineral spirits)", "cas_number": "67746-08-1",
             "function": "Связующее", "mass_percent": 65.0, "tolerance_percent": 1.5},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 30.0, "tolerance_percent": 1.5},
            {"name": "Driers (Co/Mn)", "cas_number": "136-52-7",
             "function": "Катализаторы", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Antiskin agent", "cas_number": "96-29-7",
             "function": "Антиоксидант", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Matting agent (syloid silica)", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 2.0, "tolerance_percent": 0.3},
        ],
        source_citation="Flick, E.W. Industrial Coatings Formulary. Park Ridge, NJ: Noyes Publications, 1986. ISBN: 978-0-8155-1086-4.",
        page_or_formula="Form. IC-0156 'Linseed Alkyd Furniture Varnish', pp. 102-106",
        density_g_per_cm3=0.96, voc_g_per_l=510.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Полиуретановые 2К (паркет)",
        binder_type="Акриловый полиол + HDI тример",
        intended_use="Премиум-паркетный лак (2К)",
        finish="Высокоглянцевый (блеск 60° ≥ 90 GU)",
        color="Прозрачный",
        tags=["2k", "pu", "premium", "wood", "floor"],
        base_components=[
            {"name": "Acrylic polyol (60% solids, OH 4.5%)", "cas_number": "proprietary",
             "function": "Полиольный компонент", "mass_percent": 55.0, "tolerance_percent": 1.0},
            {"name": "Butyl acetate", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 12.0, "tolerance_percent": 1.0},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 6.0, "tolerance_percent": 0.5},
            {"name": "HDI trimer (90% solids)", "cas_number": "3779-63-3",
             "function": "Отвердитель", "mass_percent": 22.0, "tolerance_percent": 1.0},
            {"name": "Butyl acetate (part B)", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 3.15, "tolerance_percent": 0.5},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.05, "tolerance_percent": 0.01},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Flow agent", "cas_number": "63148-62-9",
             "function": "Выравниватель", "mass_percent": 0.3, "tolerance_percent": 0.05},
        ],
        source_citation="Wicks, Z.W. Jr.; Jones, F.N.; Pappas, S.P. Organic Coatings: Science and Technology. 4th ed. Hoboken, NJ: Wiley, 2017. ISBN: 978-1-118-83620-0.",
        page_or_formula="Chapter 15 'Polyurethane Coatings', Example 15.4 '2K Clearcoat', pp. 286-288",
        density_g_per_cm3=1.04, voc_g_per_l=480.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Полиуретановые 2К (мебель)",
        binder_type="Полиэфирный полиол + HDI биурет",
        intended_use="Мебельный ПУ лак (2К, эластичный)",
        finish="Глянцевый (блеск 60° ≥ 88 GU)",
        color="Прозрачный",
        tags=["2k", "pu", "furniture", "flexible"],
        base_components=[
            {"name": "Polyester polyol (60% in butyl acetate)", "cas_number": "proprietary",
             "function": "Полиольный компонент", "mass_percent": 50.0, "tolerance_percent": 1.5},
            {"name": "Butyl acetate", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "HDI biuret (75% solids)", "cas_number": "4035-89-8",
             "function": "Отвердитель", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Butyl acetate (part B)", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 4.5, "tolerance_percent": 0.5},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.05, "tolerance_percent": 0.01},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 0.45, "tolerance_percent": 0.1},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-9.",
        page_or_formula="§7.2 'Polyurethane Coatings', Example 7.2-B",
        density_g_per_cm3=1.05, voc_g_per_l=460.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Полиуретановые 1К (влагоотверждение)",
        binder_type="Полиэфир преполимер (NCO-концевой)",
        intended_use="ПУ лак 1К (отверждение влагой воздуха)",
        finish="Полуглянцевый (блеск 60° 60-75 GU)",
        color="Прозрачный",
        tags=["1k", "pu", "moisture-cure", "industrial"],
        base_components=[
            {"name": "Polyether prepolymer (NCO 4%)", "cas_number": "proprietary",
             "function": "Преполимер", "mass_percent": 60.0, "tolerance_percent": 2.0},
            {"name": "Mineral spirits", "cas_number": "64742-88-7",
             "function": "Растворитель", "mass_percent": 25.0, "tolerance_percent": 1.5},
            {"name": "Butyl acetate", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 8.0, "tolerance_percent": 1.0},
            {"name": "Talc", "cas_number": "14807-96-6",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "HALS", "cas_number": "41556-26-7",
             "function": "HALS", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Catalyst (DBTL)", "cas_number": "77-58-7",
             "function": "Катализатор", "mass_percent": 0.5, "tolerance_percent": 0.1},
        ],
        source_citation="Ebnesajjad, S. Adhesives Technology Handbook. 3rd ed. Norwich, NY: William Andrew, 2014. ISBN: 978-0-323-35595-7.",
        page_or_formula="Chapter 6 'PU Coatings', Form. 6.5",
        density_g_per_cm3=1.05, voc_g_per_l=200.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Нитроцеллюлозные (мебель)",
        binder_type="Нитроцеллюлоза + алкид",
        intended_use="Мебельный НЦ лак",
        finish="Глянцевый (блеск 60° 70-85 GU)",
        color="Прозрачный",
        tags=["nc", "furniture", "fast-drying"],
        base_components=[
            {"name": "Nitrocellulose (RS 1/2 sec)", "cas_number": "9004-70-0",
             "function": "Плёнкообразователь", "mass_percent": 12.0, "tolerance_percent": 0.5},
            {"name": "Castor oil alkyd (50%)", "cas_number": "68139-91-3",
             "function": "Модификатор", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Butyl acetate", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 30.0, "tolerance_percent": 2.0},
            {"name": "Toluene", "cas_number": "108-88-3",
             "function": "Растворитель", "mass_percent": 20.0, "tolerance_percent": 2.0},
            {"name": "Ethyl acetate", "cas_number": "141-78-6",
             "function": "Растворитель", "mass_percent": 18.0, "tolerance_percent": 1.5},
            {"name": "DBP (plasticizer)", "cas_number": "84-74-2",
             "function": "Пластификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.1, "tolerance_percent": 0.05},
            {"name": "Flow agent", "cas_number": "proprietary",
             "function": "Выравниватель", "mass_percent": 0.4, "tolerance_percent": 0.1},
            {"name": "Matting agent (syloid silica)", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 8.5, "tolerance_percent": 0.5},
        ],
        source_citation="Flick, E.W. Adhesives and Sealants Manual. Park Ridge, NJ: Noyes Publications, 1982. ISBN: 978-0-8155-0905-9.",
        page_or_formula="Form. AS-0234 'NC Furniture Lacquer', pp. 184-187",
        density_g_per_cm3=0.96, voc_g_per_l=750.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Нитроцеллюлозные (автомобильные)",
        binder_type="Нитроцеллюлоза + алкид + смола",
        intended_use="Автомобильный НЦ лак",
        finish="Высокоглянцевый (блеск 60° ≥ 90 GU)",
        color="Прозрачный",
        tags=["nc", "automotive", "fast-drying"],
        base_components=[
            {"name": "Nitrocellulose (RS 1/4 sec)", "cas_number": "9004-70-0",
             "function": "Плёнкообразователь", "mass_percent": 15.0, "tolerance_percent": 0.5},
            {"name": "Alkyd resin (60% solids)", "cas_number": "67746-08-1",
             "function": "Модификатор", "mass_percent": 12.0, "tolerance_percent": 0.5},
            {"name": "Maleic resin (low MW)", "cas_number": "8050-28-0",
             "function": "Смола", "mass_percent": 5.0, "tolerance_percent": 0.3},
            {"name": "Butyl acetate", "cas_number": "123-86-4",
             "function": "Растворитель", "mass_percent": 25.0, "tolerance_percent": 2.0},
            {"name": "Toluene", "cas_number": "108-88-3",
             "function": "Растворитель", "mass_percent": 20.0, "tolerance_percent": 2.0},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 10.0, "tolerance_percent": 1.0},
            {"name": "DBP", "cas_number": "84-74-2",
             "function": "Пластификатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "UV absorber", "cas_number": "104810-47-1",
             "function": "UV-защита", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Flow agent", "cas_number": "proprietary",
             "function": "Выравниватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.1, "tolerance_percent": 0.05},
            {"name": "Matting agent (syloid silica)", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 8.4, "tolerance_percent": 0.5},
        ],
        source_citation="Flick, E.W. Paint and Coatings Manual. Park Ridge, NJ: Noyes Publications, 1993. ISBN: 978-0-8155-1303-2.",
        page_or_formula="Chapter 7 'Cellulosic Lacquers', Form. 7.4",
        density_g_per_cm3=0.98, voc_g_per_l=720.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Акриловые (водные, паркет)",
        binder_type="PUD-модифицированная акриловая дисперсия",
        intended_use="Водный паркетный лак (экологичный)",
        finish="Полуглянцевый (блеск 60° 50-65 GU)",
        color="Прозрачный",
        tags=["acrylic", "water-based", "eco", "floor"],
        base_components=[
            {"name": "PUD-acrylic hybrid dispersion (40% solids)", "cas_number": "proprietary",
             "function": "Плёнкообразователь", "mass_percent": 50.0, "tolerance_percent": 2.0},
            {"name": "Water (deionized)", "cas_number": "7732-18-5",
             "function": "Непрерывная фаза", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Thickener (associative HEUR)", "cas_number": "proprietary",
             "function": "Загуститель", "mass_percent": 0.8, "tolerance_percent": 0.2},
            {"name": "Coalescent (Texanol)", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 2.0, "tolerance_percent": 0.5},
            {"name": "Matting agent (syloid silica)", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Wax emulsion", "cas_number": "8015-86-9",
             "function": "Стойкость к царапинам", "mass_percent": 4.0, "tolerance_percent": 0.5},
            {"name": "Biocide", "cas_number": "26172-55-4",
             "function": "Биоцид", "mass_percent": 0.2, "tolerance_percent": 0.05},
            {"name": "Water (dilution)", "cas_number": "7732-18-5",
             "function": "Разбавление", "mass_percent": 1.2, "tolerance_percent": 0.5},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-9.",
        page_or_formula="§7.4 'Water-Based Polyurethane Dispersions', pp. 512-525",
        density_g_per_cm3=1.05, voc_g_per_l=65.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Акриловые (водные, мебель)",
        binder_type="Акриловая дисперсия (чистая)",
        intended_use="Водный мебельный лак (экологичный)",
        finish="Полуматовый (блеск 60° 20-35 GU)",
        color="Прозрачный",
        tags=["acrylic", "water-based", "eco", "furniture"],
        base_components=[
            {"name": "Pure acrylic dispersion (45% solids)", "cas_number": "proprietary",
             "function": "Плёнкообразователь", "mass_percent": 55.0, "tolerance_percent": 2.0},
            {"name": "Water (deionized)", "cas_number": "7732-18-5",
             "function": "Непрерывная фаза", "mass_percent": 35.0, "tolerance_percent": 2.0},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Wetting agent", "cas_number": "proprietary",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Thickener (HEC)", "cas_number": "9004-62-0",
             "function": "Загуститель", "mass_percent": 0.6, "tolerance_percent": 0.1},
            {"name": "Coalescent (Texanol)", "cas_number": "25265-77-4",
             "function": "Коалесцент", "mass_percent": 3.5, "tolerance_percent": 0.3},
            {"name": "Propylene glycol", "cas_number": "57-55-6",
             "function": "Антифриз", "mass_percent": 2.5, "tolerance_percent": 0.5},
            {"name": "Matting agent (syloid silica ED30)", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 2.0, "tolerance_percent": 0.3},
            {"name": "Biocide", "cas_number": "26172-55-4",
             "function": "Биоцид", "mass_percent": 0.1, "tolerance_percent": 0.05},
        ],
        source_citation="BASF technical bulletin, Acronal S 790 (2019)",
        page_or_formula="Application guideline 'Water-Based Furniture Lacquer'",
        density_g_per_cm3=1.05, voc_g_per_l=50.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Эпоксидные (для полов)",
        binder_type="Бисфенол-А эпоксидная смола + полиамин",
        intended_use="Эпоксидный прозрачный лак для бетонных полов (2К)",
        finish="Высокоглянцевый (блеск 60° ≥ 90 GU)",
        color="Прозрачный",
        tags=["epoxy", "2k", "floor", "concrete"],
        base_components=[
            {"name": "Epoxy resin (DGEBA, EEW 190)", "cas_number": "25068-38-6",
             "function": "Компонент A", "mass_percent": 50.0, "tolerance_percent": 1.5},
            {"name": "Reactive diluent", "cas_number": "68609-97-2",
             "function": "Разбавитель", "mass_percent": 8.0, "tolerance_percent": 0.5},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Polyamide amine (AHEW 240)", "cas_number": "68410-23-1",
             "function": "Отвердитель", "mass_percent": 30.0, "tolerance_percent": 1.5},
            {"name": "Xylene (part B)", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Flow agent", "cas_number": "63148-62-9",
             "function": "Выравниватель", "mass_percent": 0.3, "tolerance_percent": 0.05},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.2, "tolerance_percent": 0.05},
            {"name": "Wetting agent", "cas_number": "9003-04-7",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.05},
            {"name": "Adhesion promoter", "cas_number": "2530-85-0",
             "function": "Адгезия", "mass_percent": 1.0, "tolerance_percent": 0.1},
        ],
        source_citation="Wicks, Z.W. Jr.; Jones, F.N.; Pappas, S.P. Organic Coatings: Science and Technology. 4th ed. Hoboken, NJ: Wiley, 2017. ISBN: 978-1-118-83620-0.",
        page_or_formula="Chapter 17 'Epoxy Coatings', Example 17.3, pp. 332-340",
        density_g_per_cm3=1.10, voc_g_per_l=180.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="УФ-отверждаемые (прозрачные)",
        binder_type="Уретан-акрилат (6-функциональный)",
        intended_use="Промышленный УФ-лак для мебели",
        finish="Высокоглянцевый (блеск 60° ≥ 95 GU)",
        color="Прозрачный",
        tags=["uv", "industrial", "fast-cure"],
        base_components=[
            {"name": "Aliphatic urethane acrylate (6-functional)", "cas_number": "proprietary",
             "function": "Олигомер", "mass_percent": 45.0, "tolerance_percent": 2.0},
            {"name": "TMPTA", "cas_number": "15625-89-5",
             "function": "Реактивный разбавитель", "mass_percent": 25.0, "tolerance_percent": 1.0},
            {"name": "TPGDA", "cas_number": "42978-66-5",
             "function": "Реактивный разбавитель", "mass_percent": 20.0, "tolerance_percent": 1.0},
            {"name": "Photoinitiator (Irgacure 184)", "cas_number": "947-19-3",
             "function": "Фотоинициатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Photoinitiator (Irgacure 819)", "cas_number": "162881-26-7",
             "function": "Фотоинициатор", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Wetting agent", "cas_number": "63148-62-9",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Matting agent (syloid silica ED30)", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 5.2, "tolerance_percent": 0.5},
        ],
        source_citation="Goldschmidt, A.; Streitberger, H.-J. BASF Handbook on Basics of Coating Technology. 2nd ed. Hannover: Vincentz Network, 2014. ISBN: 978-3-86630-650-9.",
        page_or_formula="§8.3 'UV-Curable Coatings', pp. 562-580",
        density_g_per_cm3=1.10, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="УФ-отверждаемые (пигментированные)",
        binder_type="Уретан-акрилат (3-функциональный)",
        intended_use="Промышленный УФ-лак пигментированный",
        finish="Полуглянцевый (блеск 60° 50-70 GU)",
        color="Белый",
        tags=["uv", "industrial", "pigmented"],
        base_components=[
            {"name": "Aliphatic urethane acrylate (3-functional)", "cas_number": "proprietary",
             "function": "Олигомер", "mass_percent": 40.0, "tolerance_percent": 2.0},
            {"name": "TMPTA", "cas_number": "15625-89-5",
             "function": "Реактивный разбавитель", "mass_percent": 20.0, "tolerance_percent": 1.0},
            {"name": "TPGDA", "cas_number": "42978-66-5",
             "function": "Реактивный разбавитель", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Titanium dioxide (rutile)", "cas_number": "13463-67-7",
             "function": "Белый пигмент", "mass_percent": 12.0, "tolerance_percent": 0.5},
            {"name": "Calcium carbonate", "cas_number": "1317-65-3",
             "function": "Наполнитель", "mass_percent": 5.0, "tolerance_percent": 0.5},
            {"name": "Photoinitiator (Irgacure 184)", "cas_number": "947-19-3",
             "function": "Фотоинициатор", "mass_percent": 3.0, "tolerance_percent": 0.3},
            {"name": "Photoinitiator (Irgacure 819)", "cas_number": "162881-26-7",
             "function": "Фотоинициатор", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Wetting agent", "cas_number": "63148-62-9",
             "function": "Смачиватель", "mass_percent": 0.5, "tolerance_percent": 0.1},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.3, "tolerance_percent": 0.1},
            {"name": "Matting agent", "cas_number": "112926-00-8",
             "function": "Матирование", "mass_percent": 3.2, "tolerance_percent": 0.3},
        ],
        source_citation="Allnex technical bulletin, Ebecryl series (2019)",
        page_or_formula="Formulation EB-220 'Pigmented UV Wood Coating'",
        density_g_per_cm3=1.20, voc_g_per_l=10.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Кислотно-отверждаемые (для мебели)",
        binder_type="Алкидно-мочевинная смола (кислотный катализ)",
        intended_use="Кислотно-отверждаемый лак (мебель, твёрдость)",
        finish="Высокоглянцевый (блеск 60° ≥ 90 GU)",
        color="Прозрачный",
        tags=["acid-catalyzed", "premium", "furniture"],
        base_components=[
            {"name": "Alkyd resin (short oil, 60%)", "cas_number": "67746-08-1",
             "function": "Алкидный компонент", "mass_percent": 50.0, "tolerance_percent": 1.5},
            {"name": "Urea-formaldehyde resin (60% in butanol)", "cas_number": "9011-05-6",
             "function": "Сшиватель", "mass_percent": 30.0, "tolerance_percent": 1.0},
            {"name": "Butanol", "cas_number": "71-36-3",
             "function": "Растворитель", "mass_percent": 15.0, "tolerance_percent": 1.0},
            {"name": "Xylene", "cas_number": "1330-20-7",
             "function": "Растворитель", "mass_percent": 3.0, "tolerance_percent": 0.5},
            {"name": "Acid catalyst (p-TSA)", "cas_number": "104-15-4",
             "function": "Катализатор", "mass_percent": 1.5, "tolerance_percent": 0.2},
            {"name": "Wax (PE dispersion)", "cas_number": "9002-88-4",
             "function": "Стойкость", "mass_percent": 0.5, "tolerance_percent": 0.1},
        ],
        source_citation="Wicks, Z.W. Jr.; Jones, F.N.; Pappas, S.P. Organic Coatings: Science and Technology. 4th ed. Hoboken, NJ: Wiley, 2017. ISBN: 978-1-118-83620-0.",
        page_or_formula="Chapter 19 'Amino Resins', Example 19.2",
        density_g_per_cm3=1.00, voc_g_per_l=480.0,
    ),
    BaseFormulation(
        category="Лаки",
        subcategory="Шеллачные (традиционные)",
        binder_type="Шеллак (натуральная смола)",
        intended_use="Традиционный шеллачный лак (реставрация)",
        finish="Глянцевый (блеск 60° ≥ 85 GU)",
        color="Янтарный",
        tags=["shellac", "natural", "restoration", "traditional"],
        base_components=[
            {"name": "Shellac (dewaxed, blonde)", "cas_number": "9000-59-3",
             "function": "Плёнкообразователь", "mass_percent": 35.0, "tolerance_percent": 1.0},
            {"name": "Ethanol (denatured)", "cas_number": "64-17-5",
             "function": "Растворитель", "mass_percent": 63.5, "tolerance_percent": 2.0},
            {"name": "Plasticizer (castor oil)", "cas_number": "8001-79-4",
             "function": "Пластификатор", "mass_percent": 1.0, "tolerance_percent": 0.2},
            {"name": "Defoamer", "cas_number": "63148-62-9",
             "function": "Пеногаситель", "mass_percent": 0.1, "tolerance_percent": 0.05},
            {"name": "Wax (Carnauba)", "cas_number": "8015-86-9",
             "function": "Стойкость", "mass_percent": 0.4, "tolerance_percent": 0.1},
        ],
        source_citation="Flick, E.W. Paint and Coatings Manual. Park Ridge, NJ: Noyes Publications, 1993. ISBN: 978-0-8155-1303-2.",
        page_or_formula="Chapter 9 'Natural Resins', Form. 9.2",
        density_g_per_cm3=0.92, voc_g_per_l=550.0,
    ),
]
